yetone/avante.nvim

lua/avante/init.lua
Thanks for such an amazing plugin!
=> feat: support azure

.gitignore, README.md, lua/avante/init.lua
also fix azure default api_version
=> docs: macOS tiktoken core install

Makefile, README.md, lua/avante/init.lua, lua/tiktoken_lib.lua
=> feat(tiktoken): automatic build

lua/avante/init.lua
=> perf: make load ultra ultra fast

lua/avante/ai_bot.lua
=> fix: should not force to use OPENAI_API_KEY with provider azure

lua/tiktoken_lib.lua
correct trim cpath on loading tiktoken_lib
=> fix: correct trim path

lua/avante/init.lua
=> fix(autocmd): make sure to load tiktoken on correct events (closes #16)

lua/avante/init.lua, lua/avante/sidebar.lua, lua/avante/types.lua
=> feat(type): better hinting on nui components

lua/avante/ai_bot.lua, lua/avante/config.lua, lua/avante/diff.lua, lua/avante/init.lua, lua/avante/sidebar.lua, lua/avante/utils.lua, lua/avante/view.lua
=> feat: scrollview and tracking config and lazy load and perf

lua/avante/sidebar.lua
fix https://github.com/yetone/avante.nvim/issues/35
=> fix: codeblocks have not been synchronized

lua/avante/config.lua, lua/avante/sidebar.lua, lua/avante/types.lua
=> chore(types): add annotations for block and refresh on winchanged

lua/avante/config.lua, lua/avante/init.lua, lua/avante/range.lua, lua/avante/selection_result.lua, lua/avante/sidebar.lua
=> chore(cmd): add manual refresh and update types

lua/avante/config.lua, lua/avante/diff.lua, lua/avante/init.lua, lua/avante/selection.lua
=> feat(diff): autojump

README.md, lua/avante/ai_bot.lua, lua/avante/config.lua, lua/avante/diff.lua, lua/avante/init.lua, lua/avante/sidebar.lua
- **feat: add support for input popup of envvar**
- **chore: update README and ignore certain filetypes for popup**
=> feat(ui): add envvar popup with warnings

lua/avante/ai_bot.lua
=> fix(claude): use correct key

lua/avante/config.lua, lua/avante/sidebar.lua
=> feat(experimental): add section for behaviour

lua/avante/ai_bot.lua, lua/avante/init.lua, lua/avante/selection.lua, lua/avante/sidebar.lua
=> fix(ui): set selection per buffer and remove spinner (closes #32)

lua/avante/ai_bot.lua
af1f51455eab6ced269ec8152a0a1f1ab4ed3e3c has broken azure api_key fallback
=> fix: azure api_key fallback

lua/avante/init.lua
=> fix(event): make sure to create object during tab enter

README.md, lua/avante/ai_bot.lua, lua/avante/diff.lua, lua/avante/ui/dressing.lua
=> fix(ui): use dressing.nvim for better input support

README.md, lua/avante/ai_bot.lua, lua/avante/config.lua
The DeepSeek API reduces costs through disk caching, and DeepSeek-Coder-V2-0724 achieves GPT-4-Turbo-0409 level code capabilities with excellent math and reasoning skills.
=> feat: support deepseek

README.md, lua/avante/ai_bot.lua, lua/avante/config.lua
The Groq API with LLaMA 3.1-70B-Versatile is ideal for simpler coding tasks and speed, offering fast inference times and ease of integration.
https://github.com/user-attachments/assets/39f0287e-9a24-4e6f-9a49-1caf3246c999
=> feat: support groq

lua/avante/ai_bot.lua, lua/avante/config.lua, lua/avante/init.lua, lua/avante/sidebar.lua, lua/avante/utils.lua, lua/avante/view.lua
It should also cancel the job should the users quit the chat windows
=> refactor(ai): streaming chunks to avoid excessive redraw.

README.md, lua/avante/config.lua, lua/avante/init.lua, lua/avante/selection.lua
Address typo and control on init instead of granular.
=> fix(hint): correct variable and setup on init

README.md, lua/avante/llm.lua, lua/avante/sidebar.lua
=> fix(claude): sending state manually

README.md, lua/avante/config.lua, lua/avante/llm.lua
add support for local LLM such as ollama
=> feat(llm): support local LLM

lua/avante/llm.lua
=> fix(buffer): ignore dressing as input

lua/avante/llm.lua, lua/avante/utils/init.lua
=> fix(stream): remove auto force stream (closes #90)

lua/avante/sidebar.lua
fix https://github.com/yetone/avante.nvim/issues/80
=> fix: do not insert the stream results into user code

Makefile
=> chore(build): add options to build from source on linux

lua/avante/llm.lua
=> chore(llm): expose prompt as variable

lua/avante/config.lua
=> fix(selection): hint not apply correctly

lua/avante/sidebar.lua, lua/avante/types.lua, lua/avante/utils/init.lua
=> chore: remove unused functions and simplify with utils

lua/avante/sidebar.lua
fix https://github.com/yetone/avante.nvim/issues/99
=> fix: switch back to non-streaming update mode

lua/avante/sidebar.lua
fix https://github.com/yetone/avante.nvim/issues/110
=> feat: use devicon instead of emoji

lua/avante/llm.lua
=> chore(llm): expose types for support functions

lua/avante/llm.lua
=> chore(llm): expose parse_and_call handler (closes #105)

lua/avante/config.lua, lua/avante/llm.lua, lua/avante/utils/copilot.lua, lua/avante/utils/init.lua
=> feat(llm): copilot (closes #68)

lua/avante/llm.lua, lua/avante/utils/copilot.lua
=> chore(copilot): check for valid file in addition to plugin setup

lua/avante/llm.lua
Custom Provider should be able to take handler options to render the response.
=> fix(llm): parse_stream_data should take handler options

lua/avante/llm.lua
=> fix(type): small typo

lua/avante/config.lua, lua/avante/llm.lua
feat:
- add gemini message
- add gemini response parsing
- add options for gemini tooling and rag
- placeholder type "vertex" "gemini options for model garden expansion
=> feat: add Gemini support

lua/avante/providers/init.lua
=> fix(config): join and fold correctly

README.md, lua/avante/config.lua, lua/avante/sidebar.lua
=> feat: tab switching behaviour

lua/avante/config.lua, lua/avante/providers/azure.lua, lua/avante/providers/claude.lua, lua/avante/providers/copilot.lua, lua/avante/providers/deepseek.lua, lua/avante/providers/gemini.lua, lua/avante/providers/groq.lua, lua/avante/providers/init.lua, lua/avante/providers/openai.lua
- **fix(llm): make sure to allow passing custom module**
- **fix: correct custom class**
=> fix(llm): persistent key check for override class

lua/avante/sidebar.lua
=> fix(win): make sure to balance once entering

lua/avante/providers/init.lua
=> fix: missing spec has (fixes #161)

README.md, lua/avante/sidebar.lua
=> feat(experimental): slash commands

lua/avante/init.lua, lua/avante/selection.lua, lua/avante/sidebar.lua
=> fix(refresh): correct refresh in code buffer

lua/avante/sidebar.lua
https://github.com/yetone/avante.nvim/issues/168
=> fix: switch to an invalid window

lua/avante/config.lua, lua/avante/llm.lua, lua/avante/providers/cohere.lua, lua/avante/providers/init.lua, lua/avante/sidebar.lua
should be good set of defaults now, one in US, one in canada, and
microsoft :/
=> feat(llm): cohere support

lua/avante/sidebar.lua, lua/cmp_avante/commands.lua
=> feat: commands with cmp

lua/avante/sidebar.lua, lua/avante/utils/init.lua
fix https://github.com/yetone/avante.nvim/issues/150
=> fix: nui input cannot paste

lua/avante/floating_window.lua, lua/avante/highlights.lua, lua/avante/sidebar.lua, lua/avante/utils/init.lua
fix https://github.com/yetone/avante.nvim/issues/188 https://github.com/yetone/avante.nvim/issues/186
=> feat: use regular floating win instead of nui.input

lua/avante/config.lua, lua/avante/highlights.lua, lua/avante/sidebar.lua
Reverts yetone/avante.nvim#195
=> Revert "feat: add support of light theme"

lua/avante/sidebar.lua
=> chore(sidebar): make sure to balance win when close

lua/avante/config.lua, lua/avante/llm.lua, lua/avante/providers/azure.lua, lua/avante/providers/claude.lua, lua/avante/providers/cohere.lua, lua/avante/providers/copilot.lua, lua/avante/providers/gemini.lua, lua/avante/providers/init.lua, lua/avante/providers/openai.lua
=> feat(llm): add support for parsing secret vault

README.md, lua/avante/sidebar.lua
=> chore(icons): support mini.icons

lua/avante/config.lua, lua/avante/diff.lua, lua/avante/init.lua, lua/avante/selection.lua, lua/avante/sidebar.lua, lua/avante/utils/init.lua
=> chore(keymaps): add toggle options

lua/avante/sidebar.lua
=> fix(hint): consistent sidebar submit

lua/avante/sidebar.lua, lua/cmp_avante/commands.lua
=> chore(cmp): update slash commands sources

lua/avante/config.lua, lua/avante/providers/init.lua, lua/avante/sidebar.lua, lua/avante/types.lua
‌‌‌We should add a Lua type checker to the CI. @aarnphm
=> fix: types

lua/avante/config.lua, lua/avante/history.lua, lua/avante/init.lua, lua/avante/providers/init.lua, lua/avante/sidebar.lua
=> refactor(history): use XDG_DATA_STATE as source dir

lua/avante/llm.lua, lua/avante/providers/init.lua, lua/avante/sidebar.lua
=> fix(env): make sure to popup on nofile (fixes #211)

lua/avante/llm.lua, lua/avante/providers/init.lua
make sure we don't run into race condition, fixes #211 for sure
=> fix(providers): run sync to avoid race

lua/avante/sidebar.lua
fix https://github.com/yetone/avante.nvim/issues/215
=> fix: schedule vim api calls

lua/avante/llm.lua, lua/avante/providers/claude.lua, lua/avante/providers/init.lua
Wasn't the only one running into this issue and it's more prominent due to how these companies are handling their API usage now. Can see an example in #117. Will likely have to improve this at some point and support more cases, but these seem to be the two most common problems that people run into with no feedback
=> feat(provider): initial error handling on claude

lua/avante/providers/init.lua
=> chore(providers): add failed warning

lua/avante/highlights.lua
=> refactor: move highlights to groups with fg and bg

lua/avante/diff.lua
=> fix(diff): disable inlay in diff buffer

lua/avante/config.lua, lua/avante/providers/init.lua
=> perf: use envvar whenever possible, and use cmd only as fallback

lua/avante/floating_window.lua, lua/avante/sidebar.lua
fix https://github.com/yetone/avante.nvim/issues/235
=> fix: do not use invalid bufnr and winid

lua/avante/floating_window.lua, lua/avante/sidebar.lua, lua/avante/utils/buf_storage.lua, lua/avante/utils/init.lua, lua/avante/utils/keymap.lua
fix https://github.com/yetone/avante.nvim/issues/234
=> fix: binding shortcuts to specific buffers

Build-LuaTiktoken.ps1
Follow to https://github.com/yetone/avante.nvim/pull/241
=> chore(build): Build-LuaTiktoken.ps1

lua/avante/providers/init.lua
=> chore: ignore invalid linting

lua/avante/diff.lua, lua/avante/init.lua, lua/avante/llm.lua, lua/avante/sidebar.lua, lua/avante/tiktoken.lua, lua/avante/types.lua, lua/avante/utils/tokens.lua, lua/tiktoken_lib.lua
=> chore: persistent augroup name pattern

README.md, lua/avante/init.lua
=> chore(opts): respect user opts

lua/avante/utils.lua, lua/tiktoken_lib.lua
=> chore(utils): cleanup utils to support other than lazy.nvim

lua/avante/utils.lua
=> fix(utils): missing functions (fixes #257)

lua/tiktoken_lib.lua
=> fix(tiktoken_lib): correct matching for macos

lua/avante/providers/init.lua
=> fix(login): make sure to set var on env (fixes #264)

lua/avante/providers/init.lua, lua/avante/utils.lua
=> fix(login): make sure to set on all branch

lua/avante/config.lua, lua/avante/init.lua
=> chore(config): customize prompt prefix

lua/avante/providers/copilot.lua, lua/avante/providers/init.lua
=> perf(copilot): make signin and check keys API async

lua/avante/providers/init.lua
=> fix(env): set api via input popup (fixes #274)

lua/avante/providers/init.lua
=> fix(cmdline): popup check on fail

lua/avante/clipboard/darwin.lua, lua/avante/clipboard/init.lua, lua/avante/clipboard/linux.lua, lua/avante/clipboard/windows.lua, lua/avante/config.lua, lua/avante/llm.lua, lua/avante/providers/claude.lua, lua/avante/providers/init.lua, lua/avante/utils/init.lua, lua/avante/utils/tokens.lua
=> feat(clipboard): initial support

lua/avante/providers/openai.lua
=> feat(openai): support pasting image from clipboard

README.md, lua/avante/init.lua, lua/avante/llm.lua, lua/avante/selection.lua, lua/avante/sidebar.lua, lua/avante/utils/init.lua
https://github.com/yetone/avante.nvim/issues/273
=> feat: editing mode

lua/avante/providers/init.lua
=> fix(env): skip for setting up from local

lua/avante/providers/copilot.lua
=> fix(copilot): make sure to set integration id

lua/avante/config.lua, lua/avante/selection.lua
=> chore: cleanup typo and win options

README.md
=> docs: update keybindings and LLM

README.md, lua/avante/highlights.lua
=> feat(diff): set highlights round robin

lua/avante/providers/init.lua
=> fix(provider): key error (fixes #291)

lua/avante/config.lua, lua/avante/providers/init.lua
=> fix(local): ensure to set login to true in local (fixes #135)

lua/avante/providers/init.lua
=> fix(llm): local-first check

lua/avante/utils/init.lua
=> chore(utils): rename default titles

lua/avante/selection.lua
fix https://github.com/yetone/avante.nvim/issues/307
=> fix: end_col out of range

lua/avante/selection.lua
fix https://github.com/yetone/avante.nvim/pull/301
=> fix: indentation in first line

lua/avante/diff.lua
fix https://github.com/yetone/avante.nvim/issues/308
=> fix: diff position

lua/avante/llm.lua, lua/avante/providers/gemini.lua, lua/avante/selection.lua
fix https://github.com/yetone/avante.nvim/issues/303
=> fix: gemini

lua/avante/clipboard/darwin.lua, lua/avante/clipboard/init.lua, lua/avante/clipboard/linux.lua, lua/avante/clipboard/windows.lua, lua/avante/config.lua, lua/avante/init.lua, lua/avante/providers/claude.lua, lua/avante/providers/openai.lua, lua/avante/types.lua
=> chore(clipboard): separate logic to save as base64 and files

README.md, lua/avante/clipboard/init.lua
=> fix: check for clipboard path locally to avoid recursion

lua/avante/init.lua
=> fix(refresh): check if sidebar is available or not

after/plugin/avante.lua, lua/avante/sidebar.lua
=> fix(clipboard): set cursor to new line

lua/avante/sidebar.lua
=> fix(hint): make sure to only show hint once

lua/avante/diff.lua
=> fix(inlay): make sure to check for previous options (fixes #334)

lua/avante/providers/openai.lua
Related to https://github.com/yetone/avante.nvim/issues/121
Fixes it for OpenAI at least.
=> fix(openai): first chunk emit errors

lua/avante/diff.lua
=> fix(diff): use buffer from event for callback

lua/avante/providers/openai.lua
=> fix(style): reformat

README.md, lua/avante/clipboard.lua
refer to https://github.com/yetone/avante.nvim/issues/218#issuecomment-2316030910
=> feat(clipboard): support windows

lua/avante/providers/gemini.lua
=> chore(gemini): allow overrides from config

lua/avante/providers/claude.lua, lua/avante/providers/gemini.lua
=> feat(gemini): support vision model (closes #294)

lua/avante/clipboard.lua, lua/avante/providers/azure.lua
=> feat(azure): support vision

README.md, lua/avante/config.lua, lua/avante/diff.lua
Added `cc` which picks the conflict under the cursor, if there is one.
=> feat: pick conflict under cursor

lua/avante/diff.lua
fix https://github.com/yetone/avante.nvim/issues/357
=> fix: compatible with the situation of disabling lsp inlay_hint delay

README.md, lua/avante/config.lua, lua/avante/diff.lua
https://github.com/yetone/avante.nvim/issues/197
=> feat: choose all theirs

README.md
=> docs: cleanup installation dropdown

lua/avante/clipboard.lua
=> chore(clipboard): accept nil

lua/avante/utils/init.lua
=> chore(logs): silent safe_keymap_set to debug (fixes #376)

lua/avante/config.lua, lua/avante/utils/init.lua
=> chore(config): add silent_warning options

README.md
=> docs: add instruction for mini.deps

README.md, lua/avante/config.lua, lua/avante/providers/copilot.lua, lua/avante/providers/init.lua
=> feat(provider): add back support for copilot

README.md, lua/avante/config.lua
Minor follow-up up to #381: adding `copilot` to the README. Also sync'ing the two lists 
cc @aarnphm
=> chore(provider): update supported LLM list

lua/avante/api.lua, lua/avante/config.lua
=> fix(warning): taken into account silent_warning (fixes #385)

lua/avante/sidebar.lua
https://github.com/yetone/avante.nvim/issues/387
=> feat: support apply current code snippet

lua/avante/providers/copilot.lua
=> fix(copilot): doesn't yet support image

lua/avante/config.lua, lua/avante/llm.lua, lua/avante/providers/cohere.lua, lua/avante/providers/openai.lua
Update prompts to correct grammar
concat with table.concat to avoid overhead
=> chore(provider): use latest cohere models

lua/avante/providers/openai.lua
=> chore(openai): add back support functions for ease-of-use

lua/avante/llm.lua, lua/avante/providers/copilot.lua
=> fix(copilot): support credentials saved with copilot.vim

after/plugin/avante.lua, lua/avante/config.lua
=> fix(after): early supression of warnings (fixes #385)

after/plugin/avante.lua
=> fix(img-clip): supress verbose on AvanteInput

lua/avante/clipboard.lua
=> fix(clipboard): supress in paste_image branch

lua/avante/config.lua
fix https://github.com/yetone/avante.nvim/issues/415
=> fix: remove unnecessary alerts

plugin/avante.lua
=> fix(copilot): removes empty initialization (fixes #424)

lua/avante/config.lua, lua/avante/providers/gemini.lua, lua/avante/sidebar.lua
=> fix(gemini): check if json can be decoded

lua/avante/config.lua, lua/avante/sidebar.lua
=> revert: remove invalid configuration

lua/avante/config.lua, lua/avante/highlights.lua
=> fix(highlight): respect user bold configuration (fixes #448)

lua/avante/highlights.lua
=> fix(highlight): respect user boolean

lua/avante/api.lua, lua/avante/config.lua, lua/avante/diff.lua, lua/avante/highlights.lua, lua/avante/init.lua, lua/avante/providers/init.lua, lua/avante/selection.lua, lua/avante/sidebar.lua, lua/avante/types.lua
remove unused conflict commands.
Use plug API instead.
=> feat(api): enable customizable calls functions

README.md, autoload/avante.vim
=> fix(vim): set vimexpr for build (closes #453)

lua/avante/highlights.lua
=> fix(highlights): remove duplicates initialization

lua/avante/sidebar.lua
fix https://github.com/yetone/avante.nvim/issues/449
=> chore(sidebar): remove emoji

Makefile, lua/avante/api.lua, lua/avante/clipboard.lua, lua/avante/config.lua, lua/avante/diff.lua, lua/avante/highlights.lua, lua/avante/init.lua, lua/avante/llm.lua, lua/avante/path.lua, lua/avante/providers/azure.lua, lua/avante/providers/claude.lua, lua/avante/providers/cohere.lua, lua/avante/providers/copilot.lua, lua/avante/providers/gemini.lua, lua/avante/providers/init.lua, lua/avante/providers/openai.lua, lua/avante/selection.lua, lua/avante/sidebar.lua, lua/avante/suggestion.lua, lua/avante/tokenizers.lua, lua/avante/ui/dressing.lua, lua/avante/utils/init.lua, lua/avante/utils/root.lua, lua/avante/utils/tokens.lua, lua/avante_lib.lua, lua/cmp_avante/commands.lua, plugin/avante.lua, stylua.toml
=> chore: run stylua [generated]

lua/avante/api.lua
=> chore(types): update API to include suggestion

lua/avante/highlights.lua
=> fix(highlight): make sure to setup conflict colors

lua/avante/api.lua, lua/avante/clipboard.lua, lua/avante/config.lua, lua/avante/diff.lua, lua/avante/highlights.lua, lua/avante/init.lua, lua/avante/llm.lua, lua/avante/path.lua, lua/avante/providers/azure.lua, lua/avante/providers/claude.lua, lua/avante/providers/cohere.lua, lua/avante/providers/copilot.lua, lua/avante/providers/gemini.lua, lua/avante/providers/init.lua, lua/avante/providers/openai.lua, lua/avante/selection.lua, lua/avante/sidebar.lua, lua/avante/suggestion.lua, lua/avante/tokenizers.lua, lua/avante/utils/init.lua, lua/avante/utils/root.lua, lua/avante/utils/tokens.lua, lua/cmp_avante/commands.lua, plugin/avante.lua, stylua.toml
=> fix(style): add parentheses

.github/workflows/build.yaml, .github/workflows/ci.yaml, Makefile, README.md, autoload/avante.vim, build.sh, lua/avante/api.lua, lua/avante/init.lua
=> feat(crates): prebuilt binaries

README.md, autoload/avante.vim, build.sh, lua/avante/init.lua
=> fix(install): prebuilt instruction (closes #474)

lua/avante/init.lua
=> chore: set build from source to false

lua/avante/providers/azure.lua, lua/avante/providers/claude.lua, lua/avante/providers/openai.lua
=> chore(provider): use default value set in metaclass

.github/workflows/ci.yaml, crates/avante-templates/src/lib.rs, crates/avante-tokenizers/src/lib.rs
=> chore(rust): fix current clippy lint

lua/avante/config.lua
=> fix(lua): linter for config

lua/avante/providers/gemini.lua
=> revert(gemini): revert to gpt-4o as tokenizers (closes #499)

README.md
=> chore(readme): update install instruction

build.sh
=> fix(sh): remove set options on bash

README.md
=> chore(readme): update instructions to keep up with main

lua/avante/api.lua
=> chore(build): streaming logs

.github/workflows/release.yaml
Prerequisites for #483.
Also please release a new version after merging. @yetone
=> ci(release): archive Windows artifacts with zip

autoload/avante.vim
=> chore(vimscript): disable build from source

Build.ps1, lua/avante/api.lua
follow https://github.com/yetone/avante.nvim/issues/418
cc @aarnphm
=> chore(build): support download Windows artifacts

lua/avante/llm.lua, lua/avante/path.lua, lua/avante/providers/claude.lua, lua/avante/providers/cohere.lua, lua/avante/providers/copilot.lua, lua/avante/providers/gemini.lua, lua/avante/providers/init.lua, lua/avante/providers/openai.lua, lua/avante/templates/_context.avanterules, lua/avante/templates/_memory.avanterules, lua/avante/templates/_project.avanterules, lua/avante/templates/planning.avanterules
=> perf: support prompt-caching

lua/avante/sidebar.lua
=> chore(sidebar): decrease defer for jump

lua/avante/api.lua
=> fix(api): invalid types on defined class

lua/avante/path.lua
=> fix(avante/path): incorrect handle of windows path

lua/avante/init.lua, lua/avante/path.lua
Add support to clean unused storage for not existing files.
```lua
cmd("Clean", function()
local storage_path = require("avante.path").get_storage_path()
for _, file in ipairs(vim.fn.readdir(storage_path)) do
if file:match("%.json$") then
local sourcefile = require("avante.path").get_path_from_filename(file)
if not vim.loop.fs_stat(sourcefile) then
vim.notify("Deleting " .. storage_path .. "/" .. file)
vim.fn.delete(storage_path .. "/" .. file)
end
end
end
end, { desc = "avante: clean up" })
```
=> feat: Free storage for not existing files

lua/avante/sidebar.lua, lua/avante/utils/init.lua
=> fix(input): move hints to bottom right

autoload/avante.vim, lua/avante/api.lua, lua/avante/init.lua, lua/avante/llm.lua, lua/avante/selection.lua, lua/avante/sidebar.lua, lua/avante/suggestion.lua
also fixes installation on vim-plug
=> feat(api): support native chat mode

lua/avante/init.lua
=> chore(cmd): AvanteChat

lua/avante/api.lua, lua/avante/clipboard.lua, lua/avante/config.lua, lua/avante/init.lua, lua/avante/suggestion.lua, lua/avante/utils/init.lua, plugin/avante.lua
=> chore(mapping): add support for toggling suggestion

autoload/avante.vim
=> chore: fix join vim-plug

.github/ISSUE_TEMPLATE/bug_report.yml
=> chore: add minimal reproduction instruction

README.md
=> docs: add credits for secrets

build.sh
=> chore(script): update build script to use env

lua/avante/providers/init.lua
=> fix: initialize auto suggestions providers (closes #571)

Build.ps1
‌‌‌Since I don't have Windows, I can't verify if it's correct. Could you please help me check it, @yuchanns?
=> fix: windows build script

.github/workflows/release.yaml
=> fix: revert cargo-zigbuild

Cargo.lock, crates/avante-repo-map/Cargo.toml, crates/avante-repo-map/queries/tree-sitter-zig-defs.scm, crates/avante-repo-map/src/lib.rs
Adapted the repository's Rust code to support Zig and added the union type. All tests are passing.
=> feature: zig support for repo map

README.md, lua/avante/config.lua, lua/avante/sidebar.lua
- make apply and apply_all mappings configurable
- fixed bug where apply mapping was not unbound in unbind_apply_key
- allow apply_all mapping to be pressed anywhere in the sidebar
fixes #528
=> feat: allow pressing apply_all mapping anywhere in sidebar (#528)

lua/avante/sidebar.lua, lua/avante/utils/init.lua
I can't to reproduce #726 , but I am trying to fix it.
=> fix: failed to rename buffer

.github/workflows/ci.yaml, lua/avante/config.lua, lua/avante/init.lua, lua/avante/repo_map.lua
This PR introduces a new feature to display the repo map in a floating window. It includes key mappings and utility functions to support this feature.
=> feat: add repo map display

README.md, lua/avante/config.lua, lua/avante/sidebar.lua
A lot of people (me) go crazy with watermarks or brandstamps. Would love if this option to disable the header would be accepted. Thank you for your time.
=> feat: toggle sidebar_header

lua/avante/config.lua, lua/avante/repo_map.lua
=> fix: conflict mapping with refresh and repomap

lua/avante/providers/copilot.lua
This aims to fix the rate limits raised from copilot
This has to with refresh_tokens will trigger API for tokens whenever users enter the editor, leading to problem stated in #557 
This PR addresses this by saving said tokens to `vim.fn.stdpath('data') .. /avante/github-copilot.json`
=> fix(copilot): cached tokens to avoid rate limits (closes #557)

Cargo.lock, Cargo.toml, crates/avante-tokenizers/Cargo.toml, crates/avante-tokenizers/src/lib.rs, lua/avante/config.lua, lua/avante/providers/cohere.lua, lua/avante/tokenizers.lua
address cases such as #760, and add a few tests to tokenizers crates
=> feat(tokenizers): support parsing from public URL

.github/workflows/ci.yaml, lua/avante/providers/claude.lua, lua/avante/providers/init.lua
And only run rust actions if any rust-related files change
=> chore(type): update providers and claude hints

README.md
=> chore(docs): update notes specific for Lua

lua/avante/health.lua, lua/avante/init.lua, plugin/avante.lua
=> feat(health): support checkhealth for plugins and providers

README.md, lua/avante/config.lua, lua/avante/diff.lua
=> feat: override timeoutlen while hovering over diff

lua/avante/llm.lua
=> fix(curl): show error when XDG_RUNTIME_DIR not writable

README.md
=> docs: update note about start_insert option

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/rust.yaml
=> chore(ci): enable rust conditional check

Cargo.lock, crates/avante-repo-map/Cargo.toml, crates/avante-repo-map/queries/tree-sitter-scala-defs.scm, crates/avante-repo-map/src/lib.rs
Thanks for the amazing plugin!
This PR brings scala support to repo map
=> feat(repo_map): add scala support

lua/avante/path.lua
=> fix: don't try to read non-files

lua/avante/config.lua
=> chore(config): add default claude-haiku and claude-opus (closes #774)

README.md, lua/avante/llm.lua
=> chore(docs): update correct formatting for dropdown

lua/avante/providers/claude.lua
=> fix: claude parse response

Cargo.lock, crates/avante-repo-map/Cargo.toml, crates/avante-repo-map/queries/tree-sitter-elixir-defs.scm, crates/avante-repo-map/src/lib.rs, lua/avante/repo_map.lua
This PR brings support for Elixir in the repo map.
=> feat(repo_map): add elixir support

.github/workflows/lua.yaml, crates/avante-repo-map/src/lib.rs
after it was broken in https://github.com/yetone/avante.nvim/pull/894
=> style(repo_map): fix style

lua/avante/selection.lua
=> fix: avoid ignorable error in ubuntu 22.04+

lua/avante/providers/copilot.lua
Getting copilot refresh token will freeze the process if response takes too much time.
=> Fix: Get copilot refresh token asynchronously

crates/avante-templates/src/lib.rs, lua/avante/llm.lua, lua/avante/path.lua, lua/avante/selection.lua, lua/avante/sidebar.lua, lua/avante/suggestion.lua
Added real-time token count in the sidebar
https://github.com/user-attachments/assets/159d69df-847b-47c5-b1ed-8d025d9662ef
=> feat (tokens) add token count display to sidebar

lua/avante/providers/azure.lua
Fixes using o1-preview with Azure as a provider.
1. Copied code snippet that removes unsupported options from `openai` provider to `azure` provider.
2. Disabled streaming with o1-preview on Azure. I believe [streaming is now supported](https://community.openai.com/t/openai-o1-streaming-now-available-api-access-for-tiers-1-5/1025430/4) for both o1 and o1-preview from OpenAI, but [this does not appear to be the case](https://community.openai.com/t/do-we-also-have-streaming-support-for-azure-openai-for-o1-preview/1035400) for the Azure deployment (of o1-preview at least) which breaks the model.
3. Fixes  #990
=> fix: azure o1 unsupported options

README.md
Signed-off-by: thiswillbeyourgithub <26625900+thiswillbeyourgithub@users.noreply.github.com>
=> docs: clearer comment on how to track the github release

lua/avante/sidebar.lua
=> feat: focus to input after /clear or /reset be execuated

lua/avante/sidebar.lua, lua/avante/templates/planning.avanterules
This also happens in deepseek-v3 sometimes.
#577
=> Fix cannot apply changes

crates/avante-tokenizers/src/lib.rs
=> fix: failed to download tokernizer from HF

lua/avante/config.lua
=> fix(auto_suggestion_provider): default to claude in copilot (closes #1048)

README.md
Simple correction for the link :^)
=> doc: correct linking for Custom providers

README.md
see: https://lazy.folke.io/configuration
=> docs(README): Fix the usage instructions for lazy.nvim version

lua/avante/file_selector.lua
For reasons I don't _fully_ understand #1081 introduced an issue where adding files of different file types to the context would result in only the primary buffer's contents being sent as context. I arrived at this conclusion by running `git-bisect` and having the llm emit the first 5 lines of context files, and this was the first commit that resulted in this use case no longer working.
Having dug through the documentation I suspect that passing the entirety of `contents` in the read file path was confusing the `vim.filetype.match` call. This fix ultimately ensures that only the current file's contents are passed to the ft matcher and added to the contents table.
The first image is behavior before this fix, second image is behavior after this fix:
=> fix: proper ft detection with multiple file types in context

.luacheckrc, README.md, lua/avante/config.lua, lua/avante/file_selector.lua
This PR adds the picker in folke/snacks.nvim as a file selector.
=> feat(file_selector): add snacks picker as a file selector

lua/avante/file_selector.lua, lua/avante/repo_map.lua, lua/avante/utils/init.lua
Allows to select entire directories in addition to individual files. When a directory is selected, all contained files are automatically added to the sidebar container 
https://github.com/user-attachments/assets/9511f504-272e-40b5-bb29-6a96a4f078a6
=> feat (file_selector) Add directory selection support to file selector

Makefile
closes https://github.com/yetone/avante.nvim/issues/1154
=> Fix Makefile shell usage

lua/avante/providers/openai.lua
=> fix(providers/openai) Check for vim.NIl on tool_calls

lua/avante/api.lua, lua/avante/config.lua, lua/avante/init.lua, lua/avante/model_select.lua, lua/avante/model_selector.lua
Allows to change the model in the runtime 
https://github.com/user-attachments/assets/6a07c5db-9230-428e-942b-efd944f19b2a
=> feat(model): add model selection

lua/avante/sidebar.lua
Add the command `/commit` so people can ask AI to commit the changes.
Hanchin Hsieh <me@yuchanns.xyz>
=> feat(sidebar): add "commit" command

lua/avante/providers/claude.lua, lua/avante/providers/copilot.lua
While tinkering with my config, I saw that adding `disable_tools = true` did nothing to my claude config.
So I grabbed the code from openai and added it to claude & copilot
=> allow disabling tools for claude & copilot

README.md, lua/avante/config.lua, lua/avante/llm_tools.lua
Key changes:
- Add Kagi search engine integration with API interface
- Update configuration to include Kagi provider options
- Update documentation for Kagi search engine setup and usage
- Improve web search engine section formatting in README
=> feat: add support for Kagi search engine

lua/avante/sidebar.lua
=> Revert "fix: finally diff in cursor planning mode again (#1338)"

README.md, lua/avante/sidebar.lua
Fixes #1288 .
Please review the code with care, and feel free to change it.
I somehow feel there're other unnecessary codes if we choose to implement like this, but I'll leave you to judge.
TODO: new test cases
=> fix: use tree-sitter-markdown to extract code snippets

lua/avante/rag_service.lua, py/rag-service/src/main.py
Fix: [OpenAI host env](https://github.com/run-llama/llama_index/issues/701#issuecomment-1465061395)
Feat: add custom embedding model
=> fix: openai env

lua/avante/health.lua, lua/avante/utils/init.lua
I changed the fallback function that checked dependencies in the health script bc the healthchecks werent working outside lazy
solves #1388
=> fix: checkhealth to run outside lazy

lua/avante/llm_tools.lua
The new claude model loves calling the python tool, and and most of the time it's fine, but would prefer not to have it block the UI (similar to the bash tool).
Additionally, instead of invoking vim.fn.chdir to change the directory for the python tool, I used the cwd option for vim.system, which doesn't leave nvim in a bad state when something errors.
=> feat: run python tool asynchronously

lua/avante/templates/planning.avanterules
This PR is trying to fix #1463
=> Add instruct for creating new files

README.md
add a tip to add neotree shorcut to add selected files quickly.
=> feat: add neotree shortcut tip

lua/avante/prompt_input.lua, lua/avante/sidebar.lua
This PR aims to fix #1124
From my limited testing, it seems to cleanup the buffers now but please test it before merging.
=> fix: remove stale popup buffers

lua/avante/providers/claude.lua, lua/avante/providers/vertex_claude.lua, lua/avante/types.lua
Adds the ability to use tools when using the vertex_claude provider
=> feat: Add claude tools to vertex claude provider

lua/avante/providers/bedrock.lua, lua/avante/providers/bedrock/claude.lua, lua/avante/providers/claude.lua, lua/avante/providers/copilot.lua, lua/avante/providers/openai.lua, lua/avante/providers/vertex_claude.lua, lua/avante/types.lua
Tested with bedrock, haven't tested with claude which should have been tested, but I don't have access to claud api.
Please make sure it won't break claude.
=> feat: support tools in bedrock

README.md
=> doc: adding config line for home-manager

Build.ps1, build.sh
Fixes #1662 
Build.ps1 is still testing
=> feat: download release only when needed

README.md, README_zh.md, lua/avante/config.lua, lua/avante/llm_tools/init.lua
- Remove unnecessary blank line in README.md
- Add missing closing details tag in both README.md and README_zh.md
- Add proxy support to the web search engine configuration in config.lua
- Ensure the web search function uses the proxy setting when available in init.lua
- Fix a potential nil access in the response body format check in config.lua
=> fix: enhance web search functionality with proxy support

lua/avante/sidebar.lua, lua/avante/utils/init.lua
This pull request introduces a new utility function `Utils.is_valid_container` and refactors the `Sidebar` component to utilize it for checking the validity of NUI containers. This change simplifies the codebase by removing redundant validation logic and centralizing it into a single, reusable function.
=> refactor(Sidebar): Introduce `Utils.is_valid_container` for Unified Container Validation

lua/avante/config.lua, lua/avante/sidebar.lua
- Add the option to exclude filetypes from automatically opening the selector
https://github.com/user-attachments/assets/b7d9808c-b04b-4088-94ac-9450960b1cf9
Changed
https://github.com/user-attachments/assets/0410a0b9-5048-4f1b-a9f1-40a6d368c444
=> feat: allow excluding filetypes from selector autolaunch.

lua/avante/llm_tools/init.lua, lua/avante/rag_service.lua
More of a change for debugging purposes since the rag search has been hanging while debugging running with azure on macos. I assume rag search is pretty fast, in which case this should be a no-op in the happy path.
=> fix: rag search tool is asynchronous

lua/avante/sidebar.lua
Summary
Adds a visual mode keymap to delete multiple files at once from the "Selected Files" section in the sidebar.
Motivation
Improves efficiency by allowing batch deletion instead of removing files one by one.
=> feat(sidebar): add visual mode support for removing files

README.md
This is such a big QoL, that I tough it would be nice to include into official README :)
Amazing plugin btw, thx for the hard work.
=> chore: Update README: Add all buffer (files) as Selected Files

lua/avante/file_selector.lua, lua/avante/utils/init.lua
Allows terminal buffers to be added to the selected files list and read by the LLM
=> feat: add terminal buffers to selected files

lua/avante/history_selector.lua, lua/avante/path.lua, lua/avante/ui/selector/init.lua, lua/avante/ui/selector/providers/native.lua
I wanted to remove the history but there is no way i can remove individually. I thought it would be a good idea to have an option to remove history.
> [!NOTE]
> Only `native` selector supports this feature
Result
https://github.com/user-attachments/assets/2b204f15-a639-4ce6-8127-426bd82f1603
=> feat: remove history command

lua/avante/sidebar.lua
Prevents unwanted scrolling interruptions when user is reading previous content by checking scroll position before auto-scrolling during content updates.
Related #1899
=> feat(sidebar): improve auto-scroll to only trigger when user is at bottom

lua/avante/sidebar.lua
=> feat: show the count of selected files

lua/avante/providers/vertex_claude.lua
The vertex_claude provider was broken after #2300
=> fix: Include transform_anthropic_usage

lua/avante/providers/openai.lua
=> fix: forbidden inputs in mistral ai

lua/avante/providers/openai.lua
in qwen models, there would be errors of so called `userdata` as nil, this will fix it.
=> fix(openai): handle nil function arguments in tool calls

lua/avante/suggestion.lua, lua/avante/utils/init.lua
This set of changes does a bit of refactoring in suggestion.lua module, optimizing execution when reducing amount of context in suggestion items, and making logic more obvious.
=> Some refactors in suggestion.lua

lua/avante/file_selector.lua
Several fixes and cleanups in the file selector module.
=> File selector cleanup

lua/avante/config.lua, lua/avante/providers/vertex.lua
Updated vertex.lua to get Project ID with gcloud cli. 
Used the `GOOGLE_CLOUD_LOCATION` env variable that gemini CLI uses. 
Maybe add support for people who don't have gcloud cli.
=> Update support vertex gemini

lua/avante/templates/_gpt4-1-agentic.avanterules
FROM: https://burkeholland.github.io/posts/beast-mode-3-1/
=> feat: introduce beast-mode-3.1

lua/avante/sidebar.lua
be able to disable some keymaps with
```
prompt_logger = {
enabled = true,
next_prompt = {
normal = false,
insert = false,
},
prev_prompt = {
normal = false,
insert = false,
},
},
```
=> fix: check before set keymap

README.md
Couldn't start `avante.nvim` until I made the proposed changes from this PR.
related: #1117
=> docs: improve vim-plug installation guide

README.md, README_zh.md
=> fix(docs): incorrect installation instructions

scripts/setup-deps.sh
Before (fresh) 1m21s:
After (fresh) 27s:
Before (cached) 1m02s:
After (cached) 20s:
=> optimize: parallelize test dependencies installation

lua/avante/config.lua
=> fix: update config.lua default value for gpt-5-chat

lua/avante/suggestion.lua, lua/avante/utils/init.lua
A couple of cleanups for Utils.debounce() and Utils.throttle() as well as Utils.prepend_line_numbers().
=> A couple of cleanups

README.md, lua/avante/config.lua, lua/avante/llm.lua, tests/llm_spec.lua
It would be nice to have some kind of feil that you can define in the root of your project that injects some additional context into your prompts. It's pretty much a very simple implementation of what claude.md does for claude code
=> feat: add possibility to define a project based instruction file

lua/avante/path.lua, lua/avante/utils/init.lua, plugin/avante.lua
This PR adds project option for commands `AvantAsk` / `AvanteChat` and `AvanteChatNew`, so that user can open chat with specified project instead of project from current buffer.  It also writes project root to metadata.json for each project, and creates a common utility function `parse_args` in `utils` for those commands.
=> feat: add project root option in commands Ask/Chat/ChatNew

lua/avante/config.lua, lua/avante/highlights.lua, lua/avante/history/render.lua, lua/avante/sidebar.lua, lua/avante/types.lua, lua/avante/utils/init.lua
https://github.com/user-attachments/assets/92c8fea4-9723-43ba-9c8e-28e240f74330
=> feat(ui): expand tool use message
