yetone/avante.nvim

lua/avante/init.lua
lua/avante/utils.lua

`str:gsub` cannot correctly handle `original_content` if it contains certain Lua special symbols.
For example:
```go
package main
import "strings"
func main() {
strings.Replace("https://login.xxx.com/query?redirect=https%3A%2F%2Fxx.com", "%2F", "/", -1)
}
```
The problematic symbols are `%2` and `%3`.
Let's fix this.

fix: escape original_content

---

README.md
lua/avante/init.lua

chore: also fixed markdown lint errors
Sorry, I just noticed #2 already supports Azure after I started the change, it's quite a chore in such cases...
Thus this change mainly:
- introduce a separate config interface
- apply auth headers based on Azure or openai, instead of both

feat: add native azure openai configuration

---

lua/avante/init.lua
lua/avante/utils.lua

Reverts yetone/avante.nvim#5
@yuchanns Temporarily reverted because there will be this issue:

Revert "fix: escape original_content"

---

Makefile

In Linux Arm64, we get:
```bash
uname -m
aarch64
```

feat: support build tiktoken in Linux aarch64

---

.luarc.json
README.md
lua/avante/ai_bot.lua
lua/avante/config.lua
lua/avante/diff.lua
lua/avante/init.lua
lua/avante/sidebar.lua
lua/avante/types.lua
lua/avante/utils.lua
lua/avante/view.lua

* refactor(ui): bounding popover
* chore: update readme instructions on setting up render-markdown.nvim
* chore: align code style
* fix: incorrect type annotation
* fix: make it work with mouse movement
* fix: focus correct on render
* fix: make sure to close the view
* chore: cleanup cursor position
* docs: add notes on rc
* fix: make sure to apply if has diff
* fix: do not simulate user input
--------- …

refactor(ui): bounding popover (#13)

---

README.md
lua/avante/config.lua
lua/avante/init.lua
lua/avante/llm.lua
lua/avante/sidebar.lua

The motivation behind is to allow users ability to control the models and add support for custom vendors.
I feel like we have a good set of defaults, (OpenAI, Claude, Groq, Deepseek). So for any future vendor, such as Mistral, Perplexity, fireworks, etc. Users should maintain the code logic themselves

feat(providers): add support for custom vendors

---

README.md
lua/avante/config.lua
lua/avante/selection.lua

The default hints popup is displayed every time, which is quite annoying. 
Add a new config 'hints.enabled' to control its display.

feat(ui): add config to turn off hints popup

---

lua/avante/llm.lua

Revert "fix: construct handler opts in the parse function"

---

lua/avante/llm.lua

The `parse_stream_data` will never be called unless set to `parse_response_data`.

fix(llm): incorrect condition to call parse_stream_data

---

lua/avante/sidebar.lua

`git -C ...` command produces error on my machine if directory is not a git repository and `.avante_chat_history/` will be created in `fatal: not a git repository` folder.
PS: In my opinion this git command call isn't necessary as the `local current_dir = fn.fnamemodify(current_file, ":h")
` already returns the correct working  directory.

added a check for git root query

---

lua/avante/config.lua
lua/avante/sidebar.lua

@aarnphm 
fix https://github.com/yetone/avante.nvim/issues/168

fix: code buffer tab buttons should not be hijacked

---

lua/avante/config.lua
lua/avante/providers/openai.lua

When making requests to OpenAI, replace https://api.openai.com/v1 in the URL you’re currently using with https://gateway.ai.cloudflare.com/v1/{account_id}/{gateway_id}/openai.

fix(openai): add support for Cloudflare's AI-Gateway

---

lua/avante/config.lua
lua/avante/highlights.lua
lua/avante/sidebar.lua

Users can set a light theme by adjusting the config. This allows Avante to better match their setup if they're using a light theme, like I do. :)
Below is a preview from my own nvim

feat: add support of light theme

---

Makefile

Currently, the makefile tries to cURL an asset that is no longer part of the latest releases.
- For example, previously the release had the file `tiktoken_core-linux-luajit.so`. 
- Now, the CPU arch is part of the release asset. See https://github.com/gptlang/lua-tiktoken/releases/tag/v0.2.2
This change adds `ARCH` so that we fetch an existing asset. 
I tested this by telling `lazy` to use my own branch and the file downloaded is correct
```
➜  build git:(84fa8df) ls -lh
Permissions Size User Date Modified Name
.rw-r--r--  3.1M rkk  25 Aug 15:50  tiktoken_core.so
```

Include ARCH in asset name

---

lua/avante/providers/init.lua

When it configured with copilot only, nvim shows `Failed to setup openai. Avante won't work as expected` at start. The related code is here 
https://github.com/yetone/avante.nvim/blob/8cd87ac5de3c7e82fb39d7ab619ef9c5bb26a280/lua/avante/providers/init.lua#L254
and because copilot is [sharing some code from openai](https://github.com/yetone/avante.nvim/blob/8cd87ac5de3c7e82fb39d7ab619ef9c5bb26a280/lua/avante/providers/copilot.lua#L8), so the `setup()` for openai is called and the [`has()`](https://github.com/yetone/avante.nvim/blob/8cd87ac5de3c7e82fb39d7ab619ef9c5bb26a280/lua/avante/providers/init.lua#L240) method may report warnings if it lacks of env vars.
Therefore, a quick fix here is to call the `setup()` only when it was configured, or better to share the openai functions at a lower …

fix: don't automatically setup openai when its not the configured provider

---

Makefile

fix: remove temporary build directory before cloning in Makefile

---

lua/avante/llm.lua

Similar to the issue noted at https://github.com/yetone/avante.nvim/issues/296, the response from OpenAI models (e.g. `gpt-4o`) isn’t producing the expected outcome.
For instance, it generates:
<pre><code>
```lua
{{ modified code }}
```
</pre></code>
instead of providing the direct code, such as:
```markdown
{{ modified code }}
```
The revised prompt generally addresses the issue, though it still requires further polishing.
Moreover, I'm not sure whether a separate post-processing function is a better solution to this particular case.

refactor(llm): update edit mode prompt to avoid unnecessary code block markers

---

lua/avante/init.lua

Plugins like [folke/which-key.nvim](https://github.com/folke/which-key.nvim) can pick up descriptions of keymaps using the `desc` attribute.
It would be nice if `avante.nvim` worked with `which-key.nvim` out of the box.
This PR adds `desc` attributes for `toggle`, `edit`, and `refresh`.

chore: add desc to keymaps

---

lua/avante/selection.lua

To reproduce: `<Shift-V><Leader>ae`.
Before:
https://github.com/user-attachments/assets/0076f193-5b60-4c23-ab1a-96184d830c06
After:
https://github.com/user-attachments/assets/c237dc4c-d1ef-4820-a9a0-e4ab8e0a4c69
Notes:
- The visual block mode behavior is still wrong, but that seems lower priority.
- It seems like Avante (intentionally?) only supports editing whole lines. So it could also make sense to always use the visual line behavior as an indicator for what's actually being edited.

fix: AvanteEdit highlight for visual line mode

---

README.md
lua/avante/api.lua
lua/avante/config.lua
lua/avante/init.lua
lua/avante/utils/init.lua

By default, avante will safely set certain keymap if lazy is not yet set. 
All documented API, Plug binding as well as exposed API will be link [here](https://github.com/yetone/avante.nvim/wikis#keymaps)

feat(mapping): plug and expose API

---

lua/avante/config.lua

If img clip is installed not by lazy, it is checked agains `package.loaded` in `Util.has`. But the correct key to check there is `img-clip`, not `img-clip.nvim`.
Tested.

config.lua: improve check for `img-clip`

---

README.md
lua/avante/llm.lua
lua/avante/providers/claude.lua
lua/avante/providers/cohere.lua
lua/avante/providers/gemini.lua
lua/avante/providers/init.lua
lua/avante/providers/openai.lua
lua/avante/selection.lua
lua/avante/sidebar.lua

The new prompts do not seem to be very satisfactory, for example, there are issues with the generated code quality and overlapping line numbers. Therefore, the prompts have been rolled back for now, but the contextual functionality is still retained and will be used in the future.

fix: use the original prompts

---

lua/avante/selection.lua

fix https://github.com/yetone/avante.nvim/issues/401

fix(selection): cursor out of range when restoring

---

lua/avante/config.lua
lua/avante/sidebar.lua

#123 
Add the support of horizontal layout, you could change layout through setting `layout = "horizontal"` in setup.
example
```
function M.config()
local avante = require "avante"
avante.setup({
-- your configuration comes here
provider = "copilot",
layout = "horizontal",
})
end
```

feat: add horizontal layout

---

Makefile
lua/avante/sidebar.lua

FIX1 - sidebar was checking `(opts and opts.win.position) ... ~= nil` missing the case where opts.win = nil
FIX2 - Makefile should run the build.sh with bash, not sh, to correspond to the she-bang in `build.sh`
- previously (when bashism `set -eo pipefail` was present in `build.sh`) this was causing issues on POSIX-only shells (such as `dash` which I use for `/bin/sh`)

fix(windows): check nil

---

lua/avante/sidebar.lua

Behavior changed in #420 making the width/height calculated based on the code window, while previously it was based on the overall Neovim editor size. This caused windows to be too small when the user had multiple windows open.
Example behavior, when configured with `windows.width = 30`:
Before fix:
After fix:

fix: use `vim.o.lines`/`vim.o.columns` when calculating sidebar height/width

---

README.md
lua/avante/config.lua
lua/avante/sidebar.lua

The default settings for switching window focus in sidebar interfered with my copilot config, making it impossible to use it for writing prompts.
I kept the default bindings `<Tab>/<S-Tab>`, but added possibility for user to override it via `opts.mappings`.
Hope it's useful! :slightly_smiling_face:

Add user option for sidebar window focus mapping

---

README.md
lua/avante/highlights.lua
lua/avante/selection.lua
lua/avante/sidebar.lua

as per #563, using namespaces introduced an unwanted ordering dependency on when the base color scheme was set
Based on playing around with the split pane and reading the code, I'm pretty sure the `input_ns` namespace highlights did nothing, so everything to do with them was just removed (the removed winhighlight comment is probably when they went dead)
The `hint_ns` namespace is replaced with the `AvantePopupHint` highlight group, which by default links to `NormalFloat`
In the same vein, I added the `AvanteInlineHint` group to be able to style the hint that appears at the end of the line in visual mode, because `keyword` leads to quite obnoxious visuals by default imho.

fix(hl): use global namespace (closes #563)

---

lua/avante/init.lua

See #568.
Caused by typo of `behaviour.auto_suggestion` instead of `behaviour.auto_suggestions`.

fix: use correct non-nil variables (closes #568)

---

lua/avante/sidebar.lua

**Issue**: Running `/clear` multiple times in the sidebar triggers the following warning message:
```bash
E5108: Error executing lua: ....local/share/nvim/lazy/plenary.nvim/lua/plenary/path.lua:737: ENOENT: no such file or directory: /home/dd/.local/state/nvim/avante/__home__dd__Desktop__curl.c.json
stack traceback:
[C]: in function 'assert'
....local/share/nvim/lazy/plenary.nvim/lua/plenary/path.lua:737: in function 'write'
...t/.local/share/nvim/lazy/avante.nvim/lua/avante/path.lua:54: in function 'save'
...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1111: in function 'callback'
...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1231: in function 'handle_submit'
...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1341: in function …
```

fix(sidebar): allow /clear to be run multiple times

---

lua/avante/sidebar.lua

This update strengthens pattern matching to handle slight deviations in output introduced by local LLMs. Instead of manually adjusting templates for each LLM, we capture the most common variations to improve robustness, while ensuring compatibility with the officially supported LLM (e.g., Claude-3.5-Sonnet).
**Enhanced Pattern Matching:**
The primary pattern we are currently targeting is:
- `"Replace lines: 5-7"`
This update also captures the following common deviations:
- `" Replace lines: 5-7"` — Extra whitespace after a line break.
- `"1. Replace lines: 5-7"` — Numbered changes.
- `"1 Replace lines: 5-7"` — Numbering without punctuation.
- `"1) Replace lines: 5-7"` and `"1.) Replace lines: 5-7"` — Different numbering formats.
- `"Replace lines 5-7"` — Missing colon (`:`), now optional. …

feat(sidebar): enhance pattern matching for local LLM (closes #588)

---

lua/avante/sidebar.lua

When submitting content from the sidebar that includes Markdown with square brackets (e.g., `arr[j]`), the text was being rendered incorrectly as `arrj`, losing the brackets. 
This fix ensures that square brackets are properly escaped, so `arr[j]` is now rendered as expected in Markdown, preserving the original format: `arr[j]`.

fix(sidebar): escape square brackets

---

lua/avante/templates/planning.avanterules

Fix: https://github.com/yetone/avante.nvim/issues/588
Perhaps this [PR](https://github.com/yetone/avante.nvim/pull/589) is no longer needed.
before:
after:

fix(prompts): the key information in the prompts was incorrectly filtered out by jinja

---

lua/avante/sidebar.lua

feat(planning): supports insert code after line

---

README.md

@aarnphm why remove this?
https://github.com/yetone/avante.nvim/pull/255/files

fix: use global statusline

---

lua/avante/diff.lua
lua/avante/sidebar.lua

this fixes up two places I missed in https://github.com/yetone/avante.nvim/pull/590

fix(hl): use correct highlighting for inline hints

---

lua/avante/sidebar.lua

- Add an autocommand to unregister completion sources when leaving the buffer
- Include a description for the new autocommand for better clarity

fix #655: unregister completion source where BufLeave

---

lua/avante/llm.lua
lua/avante/providers/openai.lua

I've implemented a functionality for supporting the current 'o1' models of OpenAI. I've tested the integration with a tier 5 API access so that those that have it can also get the benefits of those powerful models.
The integration with O1 models doesn't interfere with current code and implementation for all other models from all my tests.
**IMPORTANT**: To make it work in an appropriate manner set the **model** and **timeout** for the openai provider in your configurations:
```lua
opts.openai = {
endpoint = "https://api.openai.com/v1",
model = "o1-preview",
timeout = 120000, -- Timeout in milliseconds
temperature = 1,
max_tokens = 4096,
["local"] = false,
}
```
The temperature and max_tokens are then automatically reset for you to fit the contemporary constraints of the API for the O1 …

Make O1 models work with avante#575

---

lua/avante/path.lua

Previously, as mentioned by @jackschedel in #579, running `:AvanteClear` before `:AvanteAsk` would cause an error due to missing directories. The `P.clear` function was deleting the cache and history directories, which were later needed by other commands like `:AvanteAsk`. This led to `ENOENT` errors when attempting to write to non-existent paths.
To resolve this, the fix ensures that the necessary directories (`cache` and `history`) are recreated immediately after they are cleared, preventing file write errors in subsequent commands.

fix: ensure paths are recreated after calling :AvanteClear to avoid errors

---

lua/avante/llm.lua

Fixes #672
Should have the same effect as #622, but cross-platform since this uses a tempname() provided by neovim instead.
(Somewhat surprising to me: the plenary curl wrapper checks whether the content of `body` is a file, and if so, it prepends `@` telling curl to read the file contents. See: https://github.com/nvim-lua/plenary.nvim/blob/2d9b06177a975543726ce5c73fca176cedbffe9d/lua/plenary/curl.lua#L205)
I don't think you'd want to put the logic at the provider, since you'll have to repeat it for every provider. This will work for all providers since it's just calling curl in a slightly different way.

Write curl body to a temporary JSON file

---

lua/avante/suggestion.lua

Since LLM models often do not remove backticks in their suggesting responses, particularly with smaller models, I have implemented backtick handling in the code. Please let me know your thoughts.

Handle backticks before decoding JSON

---

lua/avante/selection.lua
lua/avante/utils/init.lua

fix: https://github.com/yetone/avante.nvim/issues/688

fix: get selection range from previous visual mode

---

lua/avante/providers/openai.lua

Many OpenAI compatible alternative servers are still returning a
`finish_reason` of `eos_token` instead of `stop`. This commit adds
support for that to support more of these servers/options.

fix: support legacy finish_reason

---

README.md
lua/avante/api.lua
lua/avante/config.lua
lua/avante/init.lua
lua/avante/prompt_input.lua
lua/avante/selection.lua
lua/avante/sidebar.lua

Open a floating input similar to the "edit" input for the "ask" input. Enabled in config via `Config.windows.ask.floating` or by passing `{ floating = true }` to the `api.ask` method.
Includes logic to ensure the sidebar uses the correct buffer and selection if an existing sidebar is open for another code buffer.
Also refactored the `selection` module to extract the floating input logic into a new `PromptInput` class.
Not sure about the config options, happy to rename/move them.
Partially addresses #717 by defaulting to start in insert mode for floating input.

[Feature] Floating input

---

lua/avante/utils/init.lua

fix https://github.com/yetone/avante.nvim/issues/726

fix: cannot rename buffer

---

lua/avante/utils/init.lua

* Escape `.` in the `.git` and `.worktree` as otherwise any file, which has `<any character>git` or `<any character>worktree` would be ignored, like  anything inside `~/Source/github.com/i1skn/.....` would be ignored as it would match `/git`

fix: Add escaping characters to ignore patterns

---

lua/avante/repo_map.lua
lua/avante/utils/init.lua

* `Utils.is_same_file_ext` now matches `tsx` and `ts` both ways (before it was only only one way)
* When `.ts` files are not correctly detected as TypeScript, fallback to manual solution.
* Handle situation, when filetype is `nil` and it causes a crash as `repo_map_lib.stringify_definitions` does not handle `nil` correctly
Fixes: https://github.com/yetone/avante.nvim/issues/675

fix: Improve TS support for @codebase

---

crates/avante-repo-map/queries/tree-sitter-cpp-defs.scm
crates/avante-repo-map/src/lib.rs

- fixed C++ queries
- improved C++ definition extraction
- switched to BTreeMaps to ensure output order is stable
- added tests
- re-enabled tests for rust
Caveats: Private members are not omitted, and a lot of C++ syntax still isn't handled properly.
As a follow-up, it would be nice to support namespaces, but it seems difficult with the current structure of the code. I think it might be a good idea to refactor `extract_definitions` to make it more modular.

feat(repo-map): C++ improvements

---

lua/avante/init.lua

After switching colorschemes, some plugin elements like the diff, headers, etc., lose their color formatting. This is because the plugin's highlights are not reapplied correctly.
The plugin currently uses an autocmd for the `ColorSchemePre` event handle color scheme changes. However, this approach is not working as intended, and the documentation for `:h ColorSchemePre` suggests using it for removing highlights rather than reapplying them.
To address this issue, we can add an extra autocmd for the `ColorScheme` event. This will ensure that the plugin's highlights are reapplied after a color scheme change, restoring the correct formatting for elements like headers, diffs, etc.
I've left the original autocmd in place because I'm unsure if there are other parts of the plugin that rely on its …

fix: diff highlights doesn't reapply in colorscheme change

---

lua/avante/config.lua

The URL in config.lua was pointing to a non-existent URL and has been corrected to the correct URL.
before: https://github.com/yetone/avante.nvim/README.md#custom-providers
after: https://github.com/yetone/avante.nvim/wiki#custom-providers

chore: fix 404 url for custom providers comment

---

lua/avante/sidebar.lua

Previously, this configuration option only applied to floating ask windows.
Fixes #717

feat: consider config.windows.ask.start_insert for non-floating ask window

---

README.md
lua/avante/config.lua
lua/avante/sidebar.lua

Allows user to specify whether to focus on the "ours" or "theirs" diff after applying changes.

feat: add windows.ask.focus_on_apply config option

---

lua/avante/utils/init.lua

When using the `@codebase` flag, I encountered token exceeded errors. Upon investigation, I discovered that this issue arises because the Go project I'm working on uses a `vendor` folder for its dependencies. This folder was being included as part of the repo map, resulting in larger project context.
I am open to feedback and willing to alter the solution if this approach is not suitable. Please let me know if there are any suggestions or improvements that can be made.

fix(repo-map) go vendor included in repo map causing token limit error

---

README.md
lua/avante/config.lua
lua/avante/sidebar.lua

- Updated README.md and config.lua to include a new height option for the input window in vertical layout.
- Modified sidebar.lua to use the new configurable height instead of a hard-coded value of 8.
This change allows users to customize the height of the input window when using the vertical layout, providing more flexibility in the UI.

feat: add configurable input window height for vertical layout

---

lua/avante/providers/openai.lua

opts.message is of type AvanteLLMMessage. The message.content field should be used. Otherwise, table.concat(opts.messages) will fail.

fix(openai): add backward compat for `get_user_message`

---

lua/avante/sidebar.lua

While using telescope to open a file or `bNext` to switch buffers the user can mistakenly open a buffer in place of the avante input / avante buffers. Locking the buffers to the window seems to resolve this issue.
Alternatively, I can expose winfixbuf as a config option if that makes more sense. Please let me know if you'd like to see this changed.

fix (sidebar) lock avante input and avante buffers to the sidebar window

---

lua/avante/config.lua
lua/avante/providers/vertex.lua

Organisations or users that use the vertex AI API through google instead of the gemini API need to be able to SSO with gcloud authentication in order to use LLMs. You can see documentation for the API here, viewing the curl tab.
https://cloud.google.com/vertex-ai/generative-ai/docs/start/quickstarts/quickstart-multimodal#send-text-only-request
The vertex AI is gemini compatible (i.e it uses the same API under the hood), so we can use the same gemini parse message and response attributes. 
It would greatly help if this provider could be added, as it would allow me to use avante with models available via the vertex AI model garden.
The changes have been tested locally, and I would be happy to maintain this if the API changes as I regularly use this API and can keep track.

feat: :sparkles: Added vertex AI provider for orgs using gemini

---

README.md
lua/avante/config.lua
lua/avante/llm.lua

This PR introduces an experimental Dual Boost Mode to avante.nvim, allowing simultaneous response generation from two LLM providers (e.g., OpenAI and Claude). The outputs from these providers are included in a prompt as references for the default provider to generate a final, consolidated response.
Key Changes:
Added Dual Boost Mode configuration options.
Implemented response merging and error handling logic.
Updated stream management to support dual providers.
This feature enables users to leverage multiple providers for more robust responses.

feat: add Dual Boost Mode for Enhanced LLM Responses with Multi-Provider Support

---

README.md
lua/avante/config.lua

This pull request includes a minor correction to the documentation in the `README.md` and `lua/avante/config.lua` files to fix a typo.
Documentation correction:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L217-R217): Corrected the typo "Whow it works" to "How it works" in the description of the dual boost
* [`lua/avante/config.lua`](diffhunk://#diff-4f9ab2121e449ed4df68152ef7ca083a1cc5eaf429c39348f73119abd75a6edbL106-R106): Corrected the typo "Whow it works" to "How it works" in the configuration comments

fix(docs): correct typo in README and config.lua

---

README.md
lua/avante/config.lua
lua/avante/sidebar.lua

feat: minimal diff

---

Build.ps1

New-TemporaryFile doesn't work in cmd
More info: https://github.com/PowerShell/PowerShell/issues/14100

fix: fix installation build in powershell (windows)

---

lua/avante/providers/vertex.lua

This PR contains a small refactor to clean up the provider code a bit and improve its coding standards (I originally wrote it very quickly as a POC):
- The vertex AI API shouldn't accept a new API key name - the purpose of the api key is to authenticate the client, and that **has** to be done through the gcloud command. This removes the chance of end-users messing up interactions with the vertex API clients. 
I've added a screenshot of this working locally so there is not much doubt over how this affects functionality.

refactor(provider): :recycle: Updated API parsing logic for vertex AI

---

lua/avante/sidebar.lua

When the LLM chat output generates a codeblock as an example that can't be search/replaced in the file, the `[<a>: apply this, <A>: apply all]` hint text is displayed but the code is not applicable.
This small change prevents it being detected as a code block.
Before:
After:
Example sidebar results buffer content
~~~markdown
> refactor this package to follow best practices.
> 
> output a simple example of using this for me so that I can understand how the package is used.
I'll refactor the logger package to follow best practices and provide a clear example of usage.
Filepath: pkg/logger/logger.go
Replace lines: 1-11
```go
// Package logger provides a simple wrapper around slog with standardized configuration
package logger
import (
"errors"
"io"
"log/slog"
"os"
)
// LogLevel represents …
```

fix (sidebar) only display apply hint ext marks when code block can be replaced

---

lua/avante/sidebar.lua

Small change to apply the wrap setting to the selected code and avante input windows in the sidebar. 
If the preference is to allow the user to configure each window individually, I can implement this by extending the window configuration object to include a input and selected code wrap setting.
As always, let me know if there are any suggestions or improvements that can be made.
Before:
After:

fix(sidebar): apply windows.wrap setting to the selected code and avante input

---

lua/avante/providers/openai.lua

As of a few days ago, o1 models support streaming responses.
Please see:
https://community.openai.com/t/openai-o1-streaming-now-available-api-access-for-tiers-1-5/1025430

Enable streaming for o1 models

---

.github/workflows/release.yaml

Mentioned in issue #882 the binaries provided for linux-aarch64 are currently x86_64 architecture. 
This PR changes the GitHub CI pipeline to use QEMU to emulate aarch64 architecture to compile the right bin's.
One thing I noticed is that the pipeline step for aarch64 will now take much longer (obviously because of the emulation). 
Maybe there is a better way but I just wanted to get the ball rolling on this.

Pipline aarch64 fix

---

lua/avante/llm.lua
lua/avante/providers/init.lua

This can be used to pass additional arguments to curl, which can be helpful when working on new providers like bedrock, that can use curl arguments for authorization.

chore: allow to pass raw curl args

---

lua/avante/sidebar.lua
lua/avante/utils/file.lua

Adds support for files with multiple dots in the name and selects the default icon as a fallback when using nvim-web-devicons.
I moved the get_file_icon function into the file utils module however I'm happy to move it out again if it's not desired.
Credit to this pr for the telescope project for some of the implementation ideas. 
https://github.com/nvim-telescope/telescope.nvim/pull/2256
Before:
After:

feat (sidebar) nvim-web-devicons support files with multiple dots and unknown file types

---

lua/avante/config.lua
lua/avante/file_selector.lua

The current implementation for using `vim.ui.select` for `FileSelector` **takes 7+ seconds** to load the select interface on large repos. I decided it would be best to allow use of `fzf` or `telescope` to load a file list quickly, asynchronously and with fuzzy finding. 
I've added a config for `file_selector`:
```
--- @class AvanteFileSelectorConfig
--- @field provider "native" | "fzf" | "telescope"
file_selector = {
provider = "native",
-- Options override for custom providers
provider_opts = {},
},
```
and default provider implementations for `fzf` and `telescope`.
To use `fzf`, you would set provider to `fzf`, and likewise for `telescope`. Otherwise, leave the `file_selector` config out or set provider to "native" for default `vim.ui.select`.
**Fzf** 
`{ provider = "fzf" }` …

feat: allow configurable file select provider (fzf and telescope)

---

lua/avante/config.lua
lua/avante/file_selector.lua
lua/avante/sidebar.lua

Often while I'm working on something I'll open new buffers, browse code, and **then** decide that the context would be useful in my current Avante session.
This PR adds a configurable command that is enabled while the sidebar is open so that you can add the current buffer to the selected file context.

feat(context): add current buffer to selected file ctx

---

lua/avante/sidebar.lua
plugin/avante.lua

Usage:
```
:AvanteClear [history|memory|cache]
```
- changed default behavior from clearing the cache to clearing history.
- added args to clear history, memory or cache.
- added confirm dialog before clearing cache.

feat(AvanteClear): accept args to clear history, memory or cache

---

lua/avante/path.lua
lua/avante/repo_map.lua
lua/avante/tokenizers.lua

In this PR, I made two changes:
- Extract the initialization of the main libraries (templates, repo_map, tokenizers) into separate functions. This improves code readability and reusability.
- Fix the problem with loading libraries described below.
If the plugin loads for more than 1000ms (e.g., on a slow PC), then the templates library doesn't initialize, and the plugin doesn't work until the loading time becomes shorter.
This makes the plugin unusable on some PCs.
Set the library initialization delay below your system's plugin loading time (currently set to 1000ms) and try ask, try ask with @codebase. 
When accessing libraries, if they are not initialized, try to initialize them again.
I'm not sure, but maybe remove the initialization of libraries from setup with 1s delay and use just …

refactor & fix: improve libraries initialization

---

lua/avante/api.lua
lua/avante/config.lua
plugin/avante.lua

Useful for testing, debugging or programatically changing the file picker. Avante command for changing the file picker in neovim.

feat (file_selector) command for switching the file picker provider.

---

lua/avante/llm.lua

fix: https://github.com/yetone/avante.nvim/issues/627
There was no `Generation Complete!` message and no history files before this fix.
I think this is because there was no `on_complete` function call at callback but I'm not sure about this

fix(llm): make response ends properly

---

lua/avante/sidebar.lua

Applying and creating new files from the sidebar would result in an overlap detection error. Also fixes a rendering bug for snippets for new files and files that are outside of the llm file context.
As always, let me know if you need any improvements/changes/adjustments e.t.c.
Issue reported in: https://github.com/yetone/avante.nvim/issues/978
Before:
After:

fix (sidebar) rendering and applying snippets for new files

---

lua/avante/file_selector.lua
lua/avante/sidebar.lua

Neovim allows quickfix list to be populated in a variety of ways: grep, lsp symbol references etc. Being able to add files in the quickfix window to the LLM chat context allows for interesting workflows. For example, one could search for a symbol using the LSP integration, populate the quickfix with that list and then pass those along as context in Avante using @quickfix mention in the sidebar.
If there are no files in the quickfix list or the items do not have a file, nothing is added to the context.

feat(context): mention @quickfix to add files in qf to context

---

lua/avante/providers/copilot.lua

https://github.com/yetone/avante.nvim/issues/933
When the copilot token expired, the refresh token function would get called but it would happen async so that the completion would return a 401 since it would use still the expired token. The next request would then work because the async call to update it would then be completed. This would happen every time after the token expired, which was quite frequent since it expires every 30 min. 
This PR fixes it so it gets called synchronously, if the token is expired it will update it first before then calling the completion endpoint.

fix(copilot): refreshing copilot tokens

---

Build.ps1
build.sh

We may occasionally encounter rate limits when using plain CURL, but the gh CLI can help avoid this issue.

feat: use gh cli to download artifacts if exists

---

lua/avante/providers/openai.lua

Before this change, since `max_completion_tokens` was not set for `o` series models, the completion request sometimes times out. This PR makes sure that it converts the `max_tokens` parameter to `max_completion_tokens` for `o` series models.
I tested this change with `gpt-4o-mini`, `o1-mini` and `o3-mini`, and they all still work as expected.

fix(openai): support all `o` series models

---

lua/avante/sidebar.lua

if you have an global `<Tab><Tab>` keymap, there will be an delay when using `<Tab>`, and i think this `nowait` will be useful.

fix(switch_windows): add nowait to avoid pre-<Tab> keymap

---

README.md

This PR is created to update documentation for blink.cmp users following latest update to lazyvim distro using blink as default 
See #959 for corresponding issue

Update README.md for Blink.cmp instructions

---

lua/avante/file_selector.lua

Allows the user to select multiple at once when using the Telescope selector. Uses the default keybind of tab to select and `<CR>` confirms the selection

feat (file_selector): Add multi select

---

lua/avante/providers/copilot.lua

This PR fixes an issue where, on Windows environments with `XDG_CONFIG_HOME` set, Copilot's OAuth token cannot be found, resulting in the following error:
```
...m-data/lazy/avante.nvim/lua/avante/providers/copilot.lua:293: You must setup copilot with either copilot.lua or copilot.vim
```
The detailed stack trace is as follows:
```
- avante.nvim\lua\avante\providers\copilot.lua:120 _in_ **get_oauth_token**
- avante.nvim\lua\avante\providers\copilot.lua:293 _in_ **setup**
- avante.nvim\lua\avante\providers\init.lua:164 _in_ **setup**
- avante.nvim\lua\avante\providers\init.lua:317 _in_ **setup**
- avante.nvim\lua\avante\init.lua:367 _in_ **setup**
```
On Windows, the current implementation attempts to load the authentication file (`hosts.json` , `apps.json`) from:
``` …
```

fix(copilot): Prioritize `XDG_CONFIG_HOME` for OAuth token references on Windows

---

lua/avante/providers/gemini.lua

Fixes #1024
Reference: https://github.com/google/generative-ai-docs/blob/main/site/en/gemini-api/docs/get-started/rest.ipynb
Running the following curl:
```
curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:streamGenerateContent?alt=sse&key=$GEMINI_API_KEY" \
-H 'Content-Type: application/json' \
--no-buffer \
-d '{ "contents":[{"parts":[{"text": "Write long a story about a magic backpack."}]}]}'
```
Response:
```
data: {"candidates": [{"content": {"parts": [{"text": "Hidden amidst a world of ordinary backpacks, there existed an extraordinary one, imbued with"}],"role": "model"},"index": 0,"safetyRatings": [{"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_HATE_SPEECH","probability": "NEGLIGIBLE"},{"category": …
```

fix: Gemini not reaching end state

---

Build.ps1

`.\Build.ps1 -BuildFromSource true` was broken, because `Join-Path` was passed only one parameter

fix: Build.ps1 build from source not work

---

lua/avante/config.lua
lua/avante/sidebar.lua

Small feature addressing [Issue 973](https://github.com/yetone/avante.nvim/issues/973) to not auto-focus on the chat and be able to code or move around in the editor as the response is being generated

feat enhancement - Auto Focus Sidebar

---

lua/avante/file_selector.lua
lua/avante/sidebar.lua
lua/avante/utils/file.lua
lua/avante/utils/init.lua

support files outside of the current working directory. 
@yetone apologies for the new PR, I made some mistakes rebasing / merging the branch and it ended up being easier to just open a new PR on a clean branch.

feat (sidebar) support files outside of the current working directory.

---

lua/avante/templates/suggesting.avanterules

Change:
- Typo in suggesting.avanterules: "DON NOT" -> "DO NOT".
Was reviewing the latest changes to avante and noticed this small typo introduced in #1071, doubt it would confuse the model much anyway but figured I might as well throw in a quick fix.

fix: typo in suggesting.avanterules

---

crates/avante-repo-map/queries/tree-sitter-ruby-defs.scm
crates/avante-repo-map/src/lib.rs

I noticed the ruby parsing didn't work for most ruby files, so I adjusted the treesitter query and implemented module and class definitions with proper namespaced names. Also implemented detection of private class methods.
Check the test result for `test_ruby2`:
It parses this:
```ruby
require('jwt')
top_level_var = 1
def top_level_func
inner_var_in_func = 2
end
module A
module B
@module_var = :foo
def module_method
@module_var
end
class C < Base
TEST_CONST = 1
@class_var = :bar
attr_accessor :a, :b
def initialize(a, b)
@a = a
@b = b
super
end
def bar
inner_var_in_method = 1
true
end
private
def baz(request, params)
auth_header = request.headers['Authorization']
parts = auth_header.try(:split, /\s+/)
JWT.decode(parts.last)
end
end
end
end
```
into
```
var top_level_var
func …
```

feat: improve ruby parsing

---

lua/avante/config.lua

We need to instantiate the vendors table so the method can properly check the vendors table to resolve `lua/avante/config.lua:343: attempt to index field 'vendors' (a nil value)`
```lua
elseif M.vendors[provider] ~= nil then
return vim.deepcopy(M.vendors[provider], true)
```
Just discovered while running tests in nixpkgs, figured I'd create a PR instead of just ignoring the modules for testing.

fix(get_provider): fix nil access table for vendors

---

lua/avante/config.lua

As mentioned in 'bug: custom vendor configuration is broken (#1089)', the changes made in commit 'fix(get_provider): fix nil access table for vendors (#1074)' has broken the vendors config.
Assigning M.vendors to an empty table {} at line 267 causes the metatable set for M at line 340 to lose its effect. As a result, accessing M.vendors does not retrieve the correct vendors from the configuration but instead always accesses an empty table.
To resolve this issue, I removed the assignment statement that sets M.vendors to {}, and now everything works as expected. Additionally, to address the concern that likely prompted commit #1074, I've implemented a check before accessing M.vendors to prevent potential indexing of a nil value.

fix 'bug: custom vendor configuration is broken (#1089)'

---

lua/avante/sidebar.lua

Set different filetypes so that [edgy.nvim](https://github.com/folke/edgy.nvim) can easily identify the result buffer and the selected files buffer.

chore(sidebar): set different filetype for the selected files buffer

---

.github/workflows/release.yaml

Linux arm64 hosted runners now available for free in public repositories.
FYI: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview
Tested against: https://github.com/yuchanns/avante.nvim/actions/runs/12827307859/job/35769003270
Benifits: reducing build time from 32m to 2m.

feat(ci/release): use ubuntu-24.04-arm on aarch64

---

build.sh

There was an issue where since I'm authenticated to an enterprise Github, this refused to find the release. Even running the switch with `gh auth switch` and switching to github.com didn't resolve the issue. However, since this command's documentation shows host is an expected, optional component of the `--repo` argument, and we know this should be looking there, this avoids any trouble. Now the build and install works correctly.

Specify the host so the API always finds the release.

---

README.md
lua/avante/config.lua
lua/avante/file_selector.lua

While I think it might be a good idea to just accept a handler for picking in files, this follows the pattern that is already in place and allows a user to specify mini.pick if preferred.

Add File Selector Provider for mini.pick.

---

lua/avante/sidebar.lua

This PR fixes an issue where `avante.nvim` throws an error when a buffer is closed. The error occurs in `sidebar.lua` at line 951 because `self.result_container` becomes `nil`, leading to an attempt to index a nil value.
When `api.nvim_buf_attach()` is used to reset states on `on_detach`, `self:reset()` is called, which inadvertently clears `result_container`. This causes an error when the plugin tries to reference it later.
- Added a **nil check** before calling `self:reset()`.
- Ensured that `result_container` is always a **valid table** in `reset()`.
```lua
api.nvim_buf_attach(self.code.bufnr, false, {
on_detach = function(_, _)
self:reset()
end,
})
```
```lua
api.nvim_buf_attach(self.code.bufnr, false, {
on_detach = function(_, _)
if self and self.reset then
self:reset()
end
end,
}) …
```

Fix: Prevent nil result_container error on buffer detach

---

lua/avante/config.lua

For those who would like to or have to use GitHub Copilot, a constant notification every time they open neovim might be too annoying. I've added the same warning that's in the README.md to the `config.lua`. This should be enough of a warning to anyone who decides to use GitHub Copilot for auto_suggestions.

fix(config.lua): Remove constant warning notification about using Copilot for auto_suggestions

---

lua/avante/providers/azure.lua

It appears the Azure o series models now support streaming, like their OpenAI counterparts do. This small changes bring the Azure implementation in line with this. Coincidentally, this works around issue #1008, at least for the o series models, although it doesn't fix it.

chore: make azure o series models stream

---

lua/avante/config.lua
lua/avante/file_selector.lua

add a custom handler from config if users wish to manage this manually

fix(file_selector): make sure to flatten selected_paths if picker yields a single string

---

lua/avante/config.lua
lua/avante/sidebar.lua

Small change that makes quitting / closing the sidebar with `<Esc>` or `q`, configurable via the Avante config. This should help with reported bugs such as this: https://github.com/yetone/avante.nvim/issues/917.

feat(sidebar): move quit and close key mappings into config values.

---

lua/avante/file_selector.lua

Since #1153, mini.pick has not worked as a file selector. This both fixes that and enable multi-selection. Thanks to @echasnovski in [this suggestion](https://github.com/echasnovski/mini.nvim/discussions/1547#discussioncomment-12041625).

Allow single or multi selection with mini.pick.

---

README.md
lua/avante/config.lua
lua/avante/llm.lua
lua/avante/providers/bedrock.lua
lua/avante/providers/bedrock/claude.lua
lua/avante/providers/init.lua

As mentioned in **#419**, I was also very excited about having support for Amazon Bedrock, so I decided to work on adding it.  
I also referenced **[avante_bedrock.nvim](https://github.com/yuchanns/avante_bedrock.nvim)** for parsing the response. Thank you for the great work!
This PR introduces **support for Amazon Bedrock** as a new provider and adds the necessary implementation to integrate it into Avante.nvim. The key changes are as follows:
- `lua/avante/providers/bedrock.lua`
- Implements the **entry point for the Bedrock provider**.
- Handles API request construction and model selection.
- `lua/avante/providers/bedrock/claude.lua`
- A dedicated handler module for **Claude series** via Bedrock.
- Formats API parameters and processes responses.
- `README.md`
- Added instructions for …

Feat: Add Amazon Bedrock provider

---

lua/avante/highlights.lua

- When using a light theme, the shade function effectively converts colours to white, which can look jarring (**fixed**)
- The shade function lightens rather than darkens the colour (**partially improved** by changing a comment)
- The shade function is possibly poorly named, and should really lighten a dark colour and darken a light colour, or vice versa (**not fixed** in this PR). See suggestions below.
When using a light `colorscheme`, the shade function effectively converts every colour passed to it to white. Here is a screenshot of it before the fix in this PR:
I'm not sure what the intent of the `shade` function was meant to be, so have not fixed it to actually darken rather than lighten in this PR. Users using dark themes should not see any changes after this PR is merged.
Instead, …

Reduces the impact of the shade function when in light mode

---

lua/avante/config.lua

variable `jump_result_buffer_on_finish` is incorrectly mentioned on comment `jump_to_result_buffer_on_finish`

Fix typo on config.lua example

---

README.md

Hi!
I have added Packer import to the README (and tested it since I use it) and fixed the vim-plug imports because if we don't have "Plug 'MeanderingProgrammer/render-markdown.nvim'" avante won't work properly.
Thanks for the project, it helps a ton!
Let me know if i can help in any other way :)

Added Packer to README and fixed vim-plug imports

---

README.md
lua/avante/providers/bedrock.lua

Adds optional suport for including AWS session tokens, so that we can use temporary AWS credentials to access bedrock models.

feat: bedrock temporary credentials support

---

README.md
lua/avante/config.lua
lua/avante/llm_tools.lua

Google offers a [custom search JSON API](https://developers.google.com/custom-search/v1/overview)  with up to 100 daily free requests.
> Custom Search JSON API provides 100 search queries per day for free. If you need more, you may sign up for [billing](https://cloud.google.com/billing/docs/how-to/manage-billing-account) in the API Console. Additional requests cost $5 per 1000 queries, up to 10k queries per day.
This PR, adds google as a web_search_engine provider.

Adds google as a search engine provider

---

lua/avante/llm.lua

I've been using avante in dual boost lately and I think it can yield better results but, i just notice that when i enable the auto suggestion the times have gone crazy with 40s waiting to get a response. I notice its bc suggestion mode was using also the dual boost
This is a small change that will only enable the dual bost when in planning mode. Since I think that mode is the one that could benefit of that mode bc of higher response times but i think when you open the planner you're willing to spent time waiting for the AI to give best results, where in edit and suggest mode you want the ai to do a simple thing and do it fast

suggestion: dual-boost-only-in-planning-mode

---

lua/avante/suggestion.lua

Makes the provided suggestion history more faithful to future queries.
1. Fixes wrong indentation in the sample history
2. Adds insertSpaces and tabSize parameters to the sample history
In the future, it might make sense to also add an example with tabs to the history. When I work on a project with tab indentation, auto suggest frequently messes up while spaces seem to be fairly reliable.

fix(suggestions): make history more faithful to future input

---

lua/avante/sidebar.lua

This PR adds a member variable to the sidebar, denoting whether the LLM is currently generating a response.
The main use case I have in mind is to allow users to disable treesitter highlighting in the sidebar while generation is ongoing. Treesitter highlighting can be very expensive, to the point where it bottlenecks (relatively powerful) CPUs, even when history is relatively short, if the LLM is fast.
Anyway, I figured a general, minimal feature like this one would be preferable over a larger pull request that incorporates treesitter logic directly into avante. Users can query for the member variable in order to configure their plugins. Here is an example of how treesitter highlighting can be disabled during generation if this PR is merged:
```lua
{
"nvim-treesitter/nvim-treesitter", …
```

feat: expose whether the llm is currently generating content

---

lua/avante/sidebar.lua

This fix is required for users with vim.o.virtualedit="all". Otherwise, the cursor remains at the end of the prompt and has to be manually moved back before entering the next prompt.

fix(sidebar): reset cursor to beginning of prompt on submit

---

lua/avante/sidebar.lua

This helps user configs create branching logic depending on sidebar focus.
Concrete example use case: this allows user configs to implement a shortcut that opens/focuses the sidebar if unfocused, but closes sidebar if focused.

feat(sidebar): add sidebar:is_focused() member function

---

lua/avante/sidebar.lua

This fixes a bunch of errors I was getting when switching away from the avante sidebar and then back. Sometimes the sidebar would lose track of the various windows, and you'd get errors like this:
```
|| stack traceback:
|| 	...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:2350: in function <...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:2349>
|| Error detected while processing BufLeave Autocommands for "<buffer=294>":
|| Error executing lua callback: ...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:2398: attempt to index field 'selected_files_container' (a nil value)
```
Or this one:
```
|| stack traceback:
|| 	...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:2350: in function <...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:2349> …
```

fix(sidebar): fix various focus errors

---

lua/avante/config.lua
lua/avante/file_selector.lua

This pull request introduces enhancements to the file selector functionality in the `avante` module. The changes include defining a new interface for file selector parameters, updating the file selector provider type alias, and adding support for custom provider functions in the `FileSelector` class.
Key changes:
* [`lua/avante/config.lua`](diffhunk://#diff-4f9ab2121e449ed4df68152ef7ca083a1cc5eaf429c39348f73119abd75a6edbR8-R12): Added a new class `avante.file_selector.IParams` to define the structure of parameters for file selector providers.
* [`lua/avante/config.lua`](diffhunk://#diff-4f9ab2121e449ed4df68152ef7ca083a1cc5eaf429c39348f73119abd75a6edbL305-R310): Updated the `FileSelectorProvider` type alias to include a function type that accepts `avante.file_selector.IParams` as a …

feat(file_selector): support customized file selector method

---

Cargo.toml

Reverts yetone/avante.nvim#898
Because rust ci failed!

Revert "Update Cargo.toml with mlua dependency and features for successful bu…"

---

README.md
lua/avante/config.lua

This pull request includes updates to the `README.md` file to enhance the documentation for customizing the `file_selector` in Lua. The most important changes include adding a new alias to the `FileSelectorProvider` type and providing a detailed example of how to create a customized file selector function.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L383-R420): Added a new alias `fun(params: avante.file_selector.IParams): nil` to the `FileSelectorProvider` type.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L383-R420): Included a comprehensive example demonstrating how to specify a custom function for the `file_selector` to launch a picker and handle selected …

:memo: docs(README): update customized file_selector example

---

lua/avante/config.lua

Without this fix, tavily only searches for web content from the last 24h (without any savings in credits).
If tavily's API had an option like `time_range = "indefinite"` or similar, this wouldn't be a problem and the user could override the setting in their config... but as it stands, that's not the case. The best a user can do right now is 1 year (`time_range = "y"`), so I think it's better to remove the default config entry entirely and have the user add one if they need any time restriction.

fix(tavily): remove time restriction of 1 day

---

.cargo/config.toml

I am on a musl system and i get this error when building (due to static linking) when running `make BUILD_FROM_SOURCE=true`. 
Adding `-crt-static"` for linux-musl targets in `.cargo/config.toml` fixes this.
This is the error:
```
error: cannot produce cdylib for `avante-tokenizers v0.1.0 (/home/giuseppe/.local/share/nvim/lazy/avante.nvim/crates/avante-tokenizers)` as the target `x86_64-unknown-linux-musl` does not support these crate types
```

Fix: musl build error

---

Makefile

Reverts yetone/avante.nvim#1155
@alexbalonperin Sorry, I will reverte this PR as it cause error to bash
```
❯ make
avante_html2md.so avante_repo_map.so avante_templates.so avante_tokenizers.so
make: avante_html2md.so: No such file or directory
make: *** [Makefile:43: luajit] Error 127
```

Revert "Fix Makefile shell usage"

---

lua/avante/utils/init.lua

Sometimes the utility fails to identify the file type, leading to Rust serde deserialization errors. Therefore, we ensure it returns a non-nil file type.

fix(utils): get non-nil filetype

---

README.md
lua/avante/providers/init.lua

I believe `reasoning_effort` is already supported but it's not documented. I'm hoping this could be helpful for the people using the `o` models

docs: Add reasoning_effort docs

---

README.md

I've finished a source of blink.cmp for avante, hope this will be useful for blink users who don't want to use `blink.compat`.

doc: add blink-cmp-avante in README.md

---

README.md
lua/avante/config.lua
lua/avante/file_selector.lua

Since the `rg` / `fd` can get better performance to scan directory, I think it's better to provider a customized option for user to resolver the filepaths manually.
* fix #1276 
* fix: seems the `.gitignore` not works anymore

feat(file_selector): support customized filepaths resolver

---

lua/avante/file_selector.lua
lua/avante/sidebar.lua

I often find myself wanting to add my open buffers to the context instead of populating a quickfix and using @quickfix

feat(file_selector): add @buffers mention to add open buffers to chat context

---

lua/avante/llm.lua

Adding the new cursor-planning mode to the whitelist to enable the dual boost

fix: include cursor-planning in the whitelist for dualboost

---

lua/avante/llm.lua

Some API endpoints use strange indexing schemes for their tool deltas.
I've encountered 0-based indexing (correctly handled by avante), 1-based indexing (breaks avante), and even sparse indexing (also breaks avante).
This PR proposes to use `vim.spairs` instead of `ipairs` to iterate *in the correct order* over potentially sparse `tool_use_list`s.

fix: tool use when API returns sparse tool_use_list

---

lua/avante/utils/init.lua

This remove stopinsert from lock_buf. 
This makes my neovim usable while we're receiving results. Otherwise it would lag and be generally unusable.

Improve responsiveness while streaming generations.

---

lua/avante/llm.lua

The % is considered an scape charater in gsub
Sometimes, when the providers AIs response with code that includes the % it mess with the gsub method bc it thinks its a capture group. I change the gsub replace str to be function because when gsub is provided with a function it no longer looks for scape characters

fix: dualboost error with invalid capture

---

lua/avante/config.lua

Users using the `vertex` configuration defaults, after correctly setting `PROJECT_ID` and `REGION` in their environment variables, currently receive the following error in Avante:
```
Error: "API request failed with status 404. Body: '{\\n  \"error\": {\\n    \"code\": 404,\\n    \"message\": \"Publisher Model `projects/${PROJECT_ID}/locations/${REGION}/publishers/google/models/gemini-1.5-flash-latest` not found.\",\\n    \"status\": \"NOT_FOUND\"\\n  }\\n}'"
```
This pull requests updates the default `model` for `vertex` to use latest Gemini 1.5 Flash version `gemini-1.5-flash-002` as, unlike Gemini via Gemini API, Gemini via Vertex AI does not support the `-latest` alias. For more information, see here: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions.

fix: invalid default model name for `vertex` provider

---

README.md
lua/avante/init.lua

Avante doesn't load its libs when using home-manager on nix (or any other plugin manager really), since it can't find lazy.

fix: load avante_lib synchronously when not using lazy

---

README.md

This PR comments out the `reasoning_effort` parameter with the default lazy config in the README. Otherwise, OpenAI responds with a `400` error as the `reasoning_effort` parameter is not available with the `gpt-4o` model.
For example:
* https://platform.openai.com/docs/guides/reasoning
* [https://community.openai.com/t/o1s-reasoning-effort-parameter/1062308](https://community.openai.com/t/o1s-reasoning-effort-parameter/1062308/10)

docs: update lazy config

---

lua/avante/config.lua
lua/avante/llm_tools.lua
lua/avante/utils/init.lua
tests/llm_tools_spec.lua

I have some fish functions that I would like to be callable from the `run_command` llm tool and would prefer not to have to prompt it to use the tool or have it clutter up the confirmation dialog. Thus I add a config here to set the default shell command to be used, which was previously `sh -c`. It can be set like so:
```lua
{
run_command = {
shell_cmd = "fish -c",
},
}
```
I'd imagine this could also be used for making sure a command gets called within container which also seems useful, but worth considering if this would be the way to go about it.

feat: add shell_cmd config for run_command tool

---

lua/avante/llm_tools.lua
lua/avante/sidebar.lua
lua/avante/types.lua

Shares the tool function type into the builtin tools and dynamic tools. This makes the types slightly less accurate for some of the tools (allowing `string|nil|boolean` when the type should be `boolean` only), but removes a decent amount of boilerplate. Additionally, this allows for adding new parameters, and for my particular use case, I would like to allow certain tools to run asynchronously, specifically the `run_command` tool.
In future PRs, I would also like to make the `on_log` parameter more powerful, such as showing a floating terminal window to see terminal output. This might be too tailored to this tool, but would be a much better user experience.

chore: cleanup and share tool func type

---

lua/avante/llm_tools.lua
tests/llm_tools_spec.lua

Rename llm tool "search" to "search_keyword" as some llm provider(for example tongyi.aliyun) block the tool name "search" for some reason.

[Fix]:Rename llm-tool

---

lua/avante/api.lua
lua/avante/clipboard.lua
lua/avante/config.lua
lua/avante/diff.lua
lua/avante/file_selector.lua
lua/avante/health.lua
lua/avante/highlights.lua
lua/avante/init.lua-E
lua/avante/llm.lua
lua/avante/path.lua
lua/avante/providers/azure.lua
lua/avante/providers/bedrock.lua
lua/avante/providers/bedrock/claude.lua
lua/avante/providers/claude.lua
lua/avante/providers/cohere.lua
lua/avante/providers/copilot.lua
lua/avante/providers/gemini.lua
lua/avante/providers/init.lua
lua/avante/providers/openai.lua
lua/avante/providers/vertex.lua
lua/avante/rag_service.lua
lua/avante/selection.lua
lua/avante/sidebar.lua
lua/avante/tokenizers.lua
lua/avante/utils/init.lua
lua/avante_lib.lua
lua/cmp_avante/commands.lua
lua/cmp_avante/mentions.lua

the `x = function` way of declaring functions makes it so that there are two definitions when doing a "go to definition" action. This new syntax fixes that issue in addition to making the function definition more succinct.

chore: prefer not to use function assignment

---

lua/avante/llm_tools.lua

I encountered a couple of different issues with the python tool:
1. There was a typo in the confirm message and it is a bit unclear.
2. When docker is not installed, the tool fails and the response does not finish.
I have fixed the first issue by fixing the typo, listing out the container name, and making sure that the code starts on a new line.
The second issue was fixed by first checking if docker is installed, and if not, sending back a message to the LLM to make it clear that the Python tool should not be used. I had a bit of prompt engineering here since a simple error message here made the LLM try the python tool again with simpler python scripts.

fix: python tool message formatting and check for docker

---

lua/avante/providers/copilot.lua

The race condition may occur between file creation and the writing process, as both token file refreshing and watching are asynchronous operations.
```
...e/nvim/lazy/avante.nvim/lua/avante/providers/copilot.lua:317: Expected value but found T_END at character 1
stack traceback:
[C]: in function 'decode'
...e/nvim/lazy/avante.nvim/lua/avante/providers/copilot.lua:317: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
```

fix(copilot): fail to decode the empty token file

---

py/rag-service/src/main.py

The rag service kept trying to index `node_modules` even though it was ignored by git. Figured that the rag service wasn't ignoring it because it was written `/node_modules/` in the `.gitignore` file.
Without the leading slash it would ignore it just fine.
The fix I found was checking against the relative path, not the full path.

fix(rag_service): ignore leading slash gitignore patterns

---

lua/avante/config.lua
lua/avante/providers/azure.lua

The Azure extension for OpenAI-API has [two authentication methods](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#authentication), the standard `api-key` header, and an `Authorization` header for Microsoft Entra ID.  This PR adds the option to switch between the two.
I did not see a way to add a test for the provider options, but if you have one, happy add that!
Great project, thank you!

[Azure Provider] Support Microsoft Entra ID Authentication

---

lua/avante/model_selector.lua

`Config.providers` already includes `Config.vendors` (as per config.lua:453), meaning that the previous logic listed models from custom vendors twice.

fix: custom vendors listed twice in model selection dropdown

---

README.md

This is a helpful key map to know, and I stumbled upon it. It would be good to display it prominently

docs: Add key map for toggling the sidebar

---

lua/avante/config.lua
lua/avante/llm_tools.lua
lua/avante/sidebar.lua

Since the claude endpoint really likes to call the python tool, I've preferred to just completely disable it since it's not proved very useful for me. I've added a config to disable tools by name, which will allow me to disable the python tool. I also imagine a workflow where you add overrides to disable particular tools to be focused on particular tasks that are known, but good for LLMs to handle, e.g. refactoring across many files only really needs the rag tool, maybe some of the file search tools and the write_file tool.
closes: #1447

feat: disable tools with config

---

lua/avante/llm_tools.lua
lua/avante/utils/init.lua

Since the bash command was made async, changing directory via `vim.fn.chdir` caused pretty destructive behavior, e.g. buffers using relative paths would suddenly have empty contents. Thus we convert to using the `cwd` option to `vim.fn.jobstart` so that the working directory is only set for the command, but not for the editor.

fix: do not change cwd for async bash command

---

lua/avante/sidebar.lua

bugfix: Can't create parent folders when applying changes to create new files #1464

bugfix: Can't create parent folders when applying changes to create new files #1464

---

lua/avante/llm_tools.lua

In projects such as Go, the output binary artifacts are automatically named after the project; for instance, the binary of a project called "go-project" is also referred to as "go-project." Users generally add the project name to .gitignore to prevent these artifacts from being submitted.
Currently, the method used to check .gitignore relies on absolute paths and fuzzy matching, which can result in files being incorrectly identified as ignored:
```lua
print(("/root/go-project/aaa/bbb/ccc.go"):match("go%-project")) -- print "go-project"
```
IMO the checker should only take care of the path inside the project root

fix(llm_tools): fix permission checking to use relative path

---

lua/avante/llm.lua
lua/avante/providers/bedrock.lua
lua/avante/providers/cohere.lua
lua/avante/types.lua

Fix bedrock error on parsing
Error executing vim.schedule lua callback: ...re/nvim/lazy/avante.nvim/lua/avante/providers/claude.lua:177: attempt to index local 'content_block' (a nil value)
stack traceback:
...re/nvim/lazy/avante.nvim/lua/avante/providers/claude.lua:177: in function 'parse_response'
...e/nvim/lazy/avante.nvim/lua/avante/providers/bedrock.lua:40: in function 'parse_stream_data'
...ng/.local/share/nvim/lazy/avante.nvim/lua/avante/llm.lua:291: in function <...ng/.local/share/nvim/lazy/avante.nvim/lua/avante/llm.lua:280>
Error executing vim.schedule lua callback: ...re/nvim/lazy/avante.nvim/lua/avante/providers/claude.lua:177: attempt to index local 'content_block' (a nil value)
stack traceback:
...re/nvim/lazy/avante.nvim/lua/avante/providers/claude.lua:177: in function …

fix: pass context to provider for stream data parsing

---

README.md
lua/avante/config.lua
lua/avante/llm_tools.lua

```
:lua = require('avante.llm_tools').web_search({ query = 'how to quit vim' }, vim.print)
```

feat: add Brave Search as web search engine provider

---

lua/avante/llm.lua
lua/avante/providers/bedrock.lua

This is to handle exceptions from bedrock, one of which happens on command `@codebase`.

fix: handle bedrock exceptions

---

lua/avante/config.lua
lua/avante/model_selector.lua
lua/avante/types.lua

Added an option for a custom display name
I had the need for this option for multiple similar custom model configurations where I wanted to have more indicative titles.
```lua
vendors = {
["claude_37_tools_think"] = {
__inherited_from = "claude",
model = "claude-3-7-sonnet-latest",
display_name = "Claude 3.7 (Sonnet) with tools and thinking",
thinking = {
type = "enabled",
budget_tokens = 2048,
},
disable_tools = false,
temperature = 1,
},
["claude_37"] = {
__inherited_from = "claude",
model = "claude-3-7-sonnet-latest",
display_name = "Claude 3.7 (Sonnet)",
thinking = {
type = "disabled",
},
disable_tools = true,
},
["claude_haiku_tools"] = {
__inherited_from = "claude",
model = "claude-3-5-haiku-latest",
display_name = "Claude 3.5 (Haiku) with tools",
disable_tools = false,
}, …
```

feature model selection custom display name

---

lua/avante/utils/init.lua

As documented [here](https://www.lua.org/pil/8.4.html) the `pcall` function always returns `true` or `false` as the first value, never `nil`. Comparing it to nil introduces a bug as the `Utils.has` util will always return true.
I encountered it after investigating a bug: the avante setup was throwing an error because it was requiring `img-clip.nvim` even though it wasn't installed.
Using git bisect I was able to track the issue to commit 44e673d13202e211e579b1daaef82ee3d9bde5d9.
Following the error message indication of the exception, I identified this issue. The `Config.support_paste_image` was returning true because the `Utils.has("img-clip.nvim")` was returning true, because of the wrong comparison in the return statement [here](https://github.com/yetone/avante.nvim/blob/44e673d13202e21 …

fix: return statement of the "Utils.has", as "pcall" never returns nil

---

README.md

I think the lazy.nvim installation spec in the readme is contradicting itself 🤔 
Setting `lazy=false` means eagerly loading the plugin while `event = "VeryLazy"` suggests the plugin should be lazy loaded.
https://lazy.folke.io/spec/lazy_loading
> Plugins will be lazy-loaded when one of the following is true:
>
> * The plugin only exists as a dependency in your spec
> * It has an event, cmd, ft or keys key
> * config.defaults.lazy == true
see example
https://github.com/folke/lazy.nvim/blob/6c3bda4aca61a13a9c63f1c1d1b16b9d3be90d7a/lua/lazy/example.lua#L58-L60
I noticed this due to slow startup times.

fix: contradictory lazy.nvim installation spec

---

lua/avante/providers/copilot.lua

Attemted to fix the bug in #1513 according to brunofjesus's solution

Fix attempt to call field 'is_o_series_model' in Copilot provider

---

lua/avante/config.lua
lua/avante/sidebar.lua

The PR makes below changes
* add key mappings to close sidebar in input_container
* add autocmd to enter normal mode on leaving input_container
* add autocmd to enter insert mode on entering input_container
so that user can close sidebar in input_container directly without switching to result_container.
And the auto commands help to avoid below annoyances in result_container.

feat: add key mappings to close sidebar in input_container

---

lua/avante/llm_tools.lua
lua/avante/providers/init.lua
lua/avante/utils/environment.lua
lua/avante/utils/init.lua

Refactor environment loading logic into Utils and use it for existing provider loading, and web search where appropriate.
can be used for moving other api keys to secret loading tools vs. storing them in the config or clunkily trying to load them into the shell's environment.

feat: support cmd: loading api keys for google search APIs

---

lua/avante/repo_map.lua
lua/avante/sidebar.lua

The at codebase command was throwing errors when attempting to use it without an active buffer 
This fix adds proper validation and error handling in several key areas:
1.  repo_map.lua: Added safety checks for file extension before attempting to build or access the repo map
2. sidebar.lua: Improved error handling in file scanning operations and added proper validation for buffer operations
3. -Added graceful fallbacks when buffer information is not available

Fix - Fix thrown error when trying to use codebase with no buffer opened

---

py/rag-service/src/main.py

This PR adds functionality to skip audio and video files during the directory scanning process in the RAG service. Previously, these file types were being included in the indexing process, which could lead to unnecessary resource consumption and potential errors when attempting to process binary files.
- Added a list of common audio and video file extensions to filter during directory scans
- Modified the `scan_directory` function to check file extensions and skip audio/video files
- Added logging to indicate when files are being skipped due to their file type
- Simplified the file path handling logic for better readability and maintainability
Audio and video files:
1. Are binary in nature and not suitable for text-based indexing
2. Can be large, leading to increased memory usage and …

Skip audio and video files during directory scan in RAG Service.

---

README.md
lua/avante/config.lua
lua/avante/sidebar.lua

`<C-d>` should not be an insert mode default binding.
- `<C-d>` acts as the Delete key (remove a single letter after ther cursor) in shells including Bash and Zsh.
- After all, `<C-d>` (scroll half page) is such a commonly used key combination, and silently binding this key to something else leads to unexpected behavior. For instance, when jumping back and forth between code and Avante, users are prone to press `<C-d>` to scroll either code or the Avante generated response. When the cursor happens to jump to the input text window, `<C-d>` will close Avante and the input text users were currently drafting will be lost.
I've been bit by this like three times today. I think I won't be alone.

fix: remove `sidebar.close_from_input` default keybinding

---

py/rag-service/src/main.py

This could potentially be relaxed in the future if PDFs (and similar) documents could be converted to text form via something like pandoc in the future. But until then, I think it's good to be liberal in what gets skipped. My understanding is that the RAG service currently can deal only with text.

fix: skip more binary files than just audio/video in RAG scan

---

lua/avante/config.lua
lua/avante/providers/init.lua
lua/avante/providers/vertex_claude.lua

This pull request introduces a dedicated vertex_claude provider to enable seamless integration and utilization of the Claude model through Google Cloud's Vertex AI platform. The custom provider configuration  I posted in #764 stopped working for me so I decided to create this provider.
Added: 
- `lua/avante/provider/vertex_claude.lua` - Implements the vertex_claude provider logic.
Modified: 
- lua/avante/config.lua - Registers the new vertex_claude provider in the configuration system.
- lua/avante/providers.lua - Adds the vertex_claude provider to the provider list.
Purpose:
I posted configuration for a custom provider using Claude through Vertex in #764. This configuration stopped working for me, so I created a new provider vertex_claude

Vertex claude

---

lua/avante/providers/azure.lua

Fixes issue #1522 but for azure models.
Similarly defines `role_map` table in azure file to fix issue like #1518.
I think we should consider making the `azure` file inherit from `openai` so any new fields don't have to be copied over too e.g.:
```lua
-- Inherit from openai provider
setmetatable(M, { __index = O })
```

fix(azure): attempt to call is_o_series_model

---

lua/avante/utils/init.lua

to help identify log sources when debugging issues.
example debug output:
```
[2025-03-09 02:37:54] [AVANTE] [DEBUG] [avante.init:31] LazyConfig loaded
[2025-03-09 02:37:54] [AVANTE] [DEBUG] [avante.utils.environment:36] running command: { "secret-tool", "lookup", "service", "***", "type", "***" }
[2025-03-09 02:37:54] [AVANTE] [DEBUG] [avante.utils.environment:39] command result: {
code = 0,
signal = 0,
stderr = "",
stdout = "****"
}
````

feat: add caller information to debug logs

---

README.md

Add example avante options for [Nixvim: avante](https://nix-community.github.io/nixvim/plugins/avante/index.html)

docs: add example avante with nixvim options

---

lua/avante/llm.lua
lua/avante/providers/azure.lua
lua/avante/providers/bedrock/claude.lua
lua/avante/providers/claude.lua
lua/avante/providers/cohere.lua
lua/avante/providers/copilot.lua
lua/avante/providers/gemini.lua
lua/avante/providers/ollama.lua
lua/avante/providers/openai.lua
lua/avante/providers/vertex.lua
lua/avante/providers/vertex_claude.lua
lua/avante/types.lua

Just found bedrock exception handling is broken, we need to check stream flag from server response(`spec.body.stream`) also, rather than just depend on the provider config.

fix: Always handle the extra response outside of stream, such as the exceptions from bedrock

---

lua/avante/diff.lua

This PR is meant to fix issue #567 
The issue, for me, was that the vim.fn.hasmapto call returned 0 for cc and ca. So, they never got unmapped.

fix: buffer mappings not clearing after diff

---

lua/avante/sidebar.lua

If one is using avante.nvim with a non streaming LLM API the API response will only have a single chunk. So that if we don't update the displayed_response in the sidebar component, the output of the LLM will be removed from the sidebar when we complete the interaction with the LLM.
This commit makes sure that the displayed_response is updated for the first chunk as well as subsequent ones.

Update displayed response for the first chunk

---

lua/avante/config.lua
lua/avante/providers/openai.lua
lua/avante/types.lua

Hey there 👋 
we are using a proxy for auth which requires some extra headers with API requests, so I setup this PR for OpenAI. As I am using OpenAI can tell you that this works and I can add a `extra_headers` to the config and be fine. IDK if `extra_headers` is okay or if it should just be `headers`. After this is settled, I can also add this feature to the other providers. 
Let me know if you like this!

Add extra headers to providers

---

lua/avante/sidebar.lua

This PR fixes the cursor planning mode for extracting snippets.
I believe this is the only change that is necessary not sure if its more nuanced. 
I tested it locally and my cursor planning mode now works.

Fix: Use new treesitter syntax for cursor planning

---

lua/avante/utils/init.lua

This PR fixes incorrect line number detection when modifying CRLF-formatted files in `AvanteSelectedFiles`.  
By normalizing line endings (`\r\n` → `\n`) when reading files from disk, it ensures consistency across different platforms.
This PR addresses [yetone/avante.nvim#1621](https://github.com/yetone/avante.nvim/issues/1621).
- When reading files directly from disk, `io.open(filepath, "r")` does **not normalize CRLF (`\r\n`)**.
- However, when files are **opened in a Neovim buffer**, `vim.api.nvim_buf_get_lines()` **automatically normalizes line endings to LF (`\n`)**.
- This inconsistency causes **incorrect line number detection** when modifying files that use Windows-style line endings.
- Modify `read_file_from_buf_or_disk(filepath)` to **normalize CRLF (`\r\n`) to LF (`\n`)** when …

fix: normalize CRLF to LF in read_file_from_buf_or_disk

---

lua/avante/config.lua
lua/avante/rag_service.lua

I'm using a corporate LLM proxy that runs as it's own docker container, and exposes a port localhost. the hostname is fixed and points to 127.0.0.1, which does not work from inside the avante rag docker container, so the host needs to be mapped in, e.g.:
`--add-host corporate.proxy.lan:docker-proxy-name`
There may be other custom docker configs that aren't accounted for as well, such as additional environment variables, e.g.
`-e ANONYMIZED_TELEMTRY=False`
This new option makes this future-proof.

added optional docker args for rag service

---

README.md
cursor-planning-mode.md
lua/avante/config.lua
lua/avante/providers/azure.lua
lua/avante/providers/openai.lua
lua/avante/types.lua

Realising that a lot of this could be done through user configuration, but I feel it's better for it to be the default.
Update OpenAI and Azure parameters following new docs:
- https://learn.microsoft.com/en-us/azure/ai-services/openai/api-version-deprecation
- https://platform.openai.com/docs/api-reference/chat/create
* Update deprecated `max_tokens` to `max_completion_tokens`
* Add `reasoning_effort` for reasoning models, ignored otherwise
* Use `developer` message instead of `system` for reasoning models
* Detect whether model is reasoning (o-series) and use correct set of parameters
* Reduce duplication between OpenAI and Azure providers
* Tested with both Azure and OpenAI with both reasoning and non-reasoning models

feat: update openai/azure params

---

lua/avante/providers/azure.lua
lua/avante/providers/openai.lua

Should allow for compatibility with OpenAI API-like providers that haven't switched to the new parameter yet. Follows on from #1604

fix: do not allow max_tokens & max_completion_tokens at the same time

---

lua/avante/providers/copilot.lua
lua/avante/providers/ollama.lua

The OpenAI module method was renamed from `is_o_series_model` to `is_reasoning_model` ( [here](https://github.com/yetone/avante.nvim/commit/10ce065d9e78beaf5c8251df91733a72e94b3edc#diff-d719406bc23d21a57dbe39067e94501df3aab00d622f4d78c65d7b1c5a5809b6L70-R71) )but it's usage in copilot and Ollama providers was not updated.

refactor: rename is_o_series_model to is_reasoning_model

---

lua/avante/api.lua
lua/avante/sidebar.lua

This is to implement #928 -- Allow Chat Sidebar to Replace the Main Window (No Split).
People could use `avante` to ask random questions, and would like to have conversation happen in a large window instead of side bar, as which has a limited width.
To use this feature, add below settings
keys = {
{
"<leader>af",
function() require("avante.api").ask({no_split = true}) end,
desc = "avante: ask no split",
mode = { "n", "v" },
},
},

feat: Allow Chat Sidebar to Replace the Main Window (No Split)

---

lua/avante/rag_service.lua
py/rag-service/run.sh
py/rag-service/shell.nix
py/rag-service/src/main.py

I just changed the models the RAG service use when connecting to OpenAI to use better and cheaper ones
for the llm model gpt-4o-mini have better results in synthetic test, larger context window and also is cheaper with 0.6$ per million tokens (gpt-3.5-turbo is 1.50$ per million token)
for the embedding model text-embedding-3-small is a newer model which have a minor improvements in synthetic test but also is 5x cheaper with 0.02$ per million token (text-embedding-ada-002 is 0.10$ per million token)
the nix runner was buggy due to how the files were re-conciliated in the docker host. nix doesnt have the host part so i updated that part. also the nix was by default running in the tmp folder which is not ideal if you dont want to spend tokens like crazy each time you reset your computer
I …

fix: RAG services improvements

---

README.md
lua/avante/api.lua
lua/avante/config.lua
lua/avante/init.lua
lua/avante/llm.lua
lua/avante/llm_tools.lua
lua/avante/types.lua
lua/avante/ui/confirm.lua
plugin/avante.lua

solves #1531 
Adds a new binding `<leader>aS` and a new cmd `AvanteStop` that cancels any generation/tool use

feat: stop command

---

lua/avante/highlights.lua
lua/avante/utils/init.lua

If any of the avante highlight groups are configured as links to different highlight groups, then the internals of retrieving highlights and detecting background fallback stuff breaks. This makes sure to get the final highlight values of `fg/bg` rather than just `link = "x"`

fix: make sure to get the final highlight values rather than link names

---

lua/avante/highlights.lua
lua/avante/utils/init.lua

Follow up to #1682
Rather than duplicating the code for getting highlights without links. We can utilize the `avante.utils` module to simplify the code and improve maintainability.

refactor: utilize `Utils.get_hl` to minimize duplicate code

---

lua/avante/llm.lua

this pull request makes avante.nvim support the following two kinds of sse format:
```
event: something
event:something
data: something
data:something
```
currently,  avante.nvim only supports sse like following:
```
event: something
data: something
```
some claude provider will remove the space after sse type, which makes  avante.nvim won't be able to render the content.
related issue: https://github.com/yetone/avante.nvim/issues/1403

feat: more robust sse content regex

---

README.md
lua/avante/config.lua
lua/avante/ui/prompt_input.lua

The `<esc>` on normal mode is inconvenient for me since I have a bad habit of pressing the `<esc>` multipe times to ensure back to normal mode. So I want to have a chance to customize the `cancel` keymaps.

improve: support to customize the keymaps for cancelling the editing

---

lua/avante/file_selector.lua

This PR fixes an issue where valid buffers weren't being correctly added to the file selector. 
Previously, we were only checking if buffers were loaded, but this missed buffers that were valid but not visible in a window. The fix changes the condition from `vim.api.nvim_buf_is_loaded()` to a combination of `vim.api.nvim_buf_is_valid()` and `vim.bo[bufnr].buflisted`, ensuring we capture all appropriate buffers regardless of their visibility status.

fix: buffer selection logic to include all listed buffers

---

lua/avante/api.lua
lua/avante/config.lua
lua/avante/file_selector.lua
lua/avante/init.lua

This PR exposes `FileSelector:add_buffer_files()` to be used in keyboard mapping. 
It introduces a new API function `add_buffer_files()`, a dedicated keycap `<leader>aB`, and fixes an inconsistent property naming issue between `selected_files` and `selected_filepaths`.
The idea is to streamline the workflow where one opens Neovim, loads the session with open buffers and immediately wants to start a conversation with the open files.
I'm not sure if specifying the keymap (`<leader>aB`) in the plugin is the best idea, so I'm open to suggestions to maybe just leave the functionality exposed without the keymap as it's easy to set in the config.

feat: add command to include all buffer files in file selector

---

lua/avante/config.lua

The maximum token output for Haiku is 8192 tokens, see [here](https://docs.anthropic.com/en/docs/about-claude/models/all-models). Currently, if you attempt to use this provider, you get an error response from the API call.

fix: correct max_tokens for Claude 3.5 Haiku

---

lua/avante/config.lua

docs ref for max output tokens:
https://ai.google.dev/gemini-api/docs/models#gemini-2.0-flash
Token limits[*]
Input token limit
1,048,576
Output token limit
8,192

fix: update gemini max_tokens and use gemini-2.0-flash model

---

lua/avante/utils/init.lua

Resolves #1553
Tested with running `biome` in a React Native config which doesn't just result in Powershell error anymore
Before
After
Typically the workflow for WSL users is everything dev-related within the Linux system itself, powershell is rarely touched. This could be a config option in the user to configure the shell for the tool to use.

fix(wsl): wsl should prefer the defined shell instead of powershell.exe

---

lua/avante/providers/openai.lua

Copy `max_tokens` to `max_completion_tokens` for openai reasoning models
Fixes https://github.com/yetone/avante.nvim/issues/1762
Tested against my branch with `o3-mini`

fix max_tokens for reasoning models

---

lua/avante/clipboard.lua
lua/avante/config.lua

Currently the **img_clip** options are hardcoded. I'd like to add the ability to update the options. Specifically the `url_encode_path` is not working for me, and I'd like to set this to `false` as well as update the `template`.

feat: allow overriding img_paste options

---

lua/cmp_avante/commands.lua

I'm not sure of the reason, but based on my observations, `nvim-cmp` works well. However, with `blink.cmp`, the completion menu also functions properly, but once I select a command and accept it, Neovim exits immediately. I don't know how to view error messages; if you need them, please let me know.
The crash command caused by the `api.nvim_buf_set_lines(sidebar.input_container.bufnr, 0, -1, false, vim.split(content, "\n"))`

fix(blink.cmp): crash on run slash commands

---

lua/avante/init.lua

Small quality of life improvement, mostly for people who use sessions and/or don't want to have to `:qa` to exit if avante is open (me).
Before, if the Avante sidebar was open and you try to close the last open buffer, it closes the sidebar instead and blocks vim exit with an error. If you force quit `:qa!`, then if you restore the session you get a bunch of dead windows.
Fixed these issues by just adding an autocmd on QuitPre to check if the last non avante sidebar window is being closed, and if so gracefully close the sidebar first.
See vids for more context:
https://github.com/user-attachments/assets/9255e9e8-e85a-49a7-8179-8ca89bde8100
https://github.com/user-attachments/assets/56ebba5a-d26f-4dcf-bc95-325a56982b8c
https://github.com/user-attachments/assets/96795423-fbe1-4c4c-9d23-76293 …

Close avante sidebar before vimexit (fixes sessions)

---

README.md
README_zh.md
lua/avante/config.lua
lua/avante/llm_tools/init.lua

Adds support for the [SearXNG search api](https://docs.searxng.org/dev/search_api.html) to web_search tools.
This tool is a bit different from the other ones because it doesn't have an API key, but it does require you to set an api url (since it's usually a self-hosted thing).
Closes #1370

Add support for searxng

---

lua/avante/selection.lua

This PR removes the redundant CursorMovedI event from the autocmd in the Selection:setup_autocmds() function. The event is unnecessary because:
1. Visual mode and Insert mode are mutually exclusive in Vim/Neovim
2. Mode transitions are already handled by the existing ModeChanged autocmd
3. The shortcuts popup is already properly closed when exiting visual mode
This change improves code maintainability without affecting functionality.

fix: Remove unnecessary CursorMovedI event handler

---

lua/avante/config.lua
lua/avante/sidebar.lua

the new config looks like following:
```
{
windows = {
fillchars = "eob: ",
},
}
```

feat(windows): add fillchars option for the windows

---

lua/avante/ui/prompt_input.lua

Optimize autocmd management logic in the PromptInput component:
- Merge similar ModeChanged events to reduce code duplication
- Remove redundant autocmd deletion operations
- Fix incorrect conditional logic
- Simplify code structure while maintaining the same functionality
The original code attempted to individually delete autocmds after calling cancel(), which was unnecessary since cancel() calls close() which already removes the entire augroup. The refactored code maintains the same functionality but is more concise and reliable.

refactor(PromptInput): optimize PromptInput autocmd management

---

lua/avante/sidebar.lua

Fixes https://github.com/yetone/avante.nvim/issues/1577
First commit drops the `wincmd =` calls and seems straightforward to me, I'm not sure what the reasoning was to add them previously in https://github.com/yetone/avante.nvim/pull/160 and https://github.com/yetone/avante.nvim/pull/198.
Second commit drops the `nvim_win_set_width` call in `adjust_result_container_layout()`, at first I was unsure about this but after testing a bit more and trying different approaches I think it makes sense too: As I understand it the plugin wants to adjust the size of the results container in response to changes to the selected code and files, and this only seems necessary in vertical layout where we want to adjust the height. In horizontal layout the width seems like it should be static so we don't need …

Fixes to adjusting window sizes

---

lua/avante/config.lua

Bedrock Claude 3.7 use the same anthropic version. The tricky part is model id should use `us.anthropic.claude-3-7-sonnet-20250219-v1:0` in order for it to work. Hopefully this will solve the pain for bedrock users
```
{
"modelId": "anthropic.claude-3-7-sonnet-20250219-v1:0",
"contentType": "application/json",
"accept": "application/json",
"body": {
"anthropic_version": "bedrock-2023-05-31",
"max_tokens": 200,
"top_k": 250,
"stop_sequences": [],
"temperature": 1,
"top_p": 0.999,
"messages": [
{
"role": "user",
"content": [
{
"type": "text",
"text": "hello world"
}
]
}
]
}
}
```
- `<leader>a?` should be able to select the model
- be able to use the model in configuration too
```
opts = {
-- add any opts here
-- for example
provider = "bedrock",
bedrock = {
model = …
```

feat: add Bedrock Claude 3.7 Sonnet model configuration

---

lua/avante/diff.lua

SO!
Basically I noticed that when I got SEARCH/REPLACE suggestions and I wanted to go next to the next occurrence "]x"
the plugin did not actually sent me to the next ocurrence, it stayed in the current position of the file.
I implemented a small change to fix the "find_next" Lua function of the plugin.
With this change, the find_next shortcut works as expected

Fix find next on diff view

---

lua/avante/llm_tools/bash.lua
lua/avante/llm_tools/init.lua

- Remove advertising links and co-author tag from commit messages
As it is mentioned in #1831 most people don't see the value in advertising avante in git commits and having to manually edit each commit after the tool is wasting time. 
Plus It could cause trouble for people working in production environments 
Edit: From this pr I also realized that generated with avante.nvim message sticks in PRs as well which could cause a bigger issue since the edits are public
🤖 Generated with [avante.nvim](https://github.com/yetone/avante.nvim)

Remove advertising from commit messages

---

lua/avante/config.lua
lua/avante/providers/ollama.lua
lua/avante/types.lua

the default timeout (5m) isn't large enough for my use case. i would rather prefer to keep the model in memory for longer to avoid the process of reloading it.
this commit introduces the ollama `keep_alive` configuration, the default is set to 5 minutes (that is the default for ollama).

feat: add config for ollama keep alive

---

lua/avante/utils/init.lua

This change fixes avante's sidebar starting out in normal mode when being freshly opened (as opposed to re-focused), despite `start_insert = true`.

fix(utils): when locking a buffer, only stopinsert if buffer is current

---

lua/avante/providers/azure.lua

Tool usage seems to be implemented for openai, but not for azure which uses the same api. Updates the provider request to use tools.

fix: add support for tool usage for azure openai

---

lua/avante/providers/init.lua

this is implemented anyways everywhere else I looked anyways
Closes #1891

fix: allow fields like api_key_name to be a table

---

lua/avante/sidebar.lua

- Add boundary check to prevent negative line numbers when using sidebar
- Use math.max to ensure line number is always >= 0
- Fixes 'Invalid line: out of range' error that occurs when sidebar is invoked through advanced shortcuts configuration described in https://github.com/yetone/avante.nvim/wiki/Recipe-and-Tricks#advanced-shortcuts-for-frequently-used-queries-756

fix: prevent extmark line number from being negative in render_state

---

lua/avante/sidebar.lua

The selected code is not highlighted correctly in the sidebar chat history view because there is not space between the filetype and the filepath. This adds that to make the syntax highlighting work again.

fix(sidebar): correct syntax highlighting for selected code

---

stylua.toml

Since there are `goto` statements with labels in the repo, we need lua52
syntax, so it would be best to enforce this syntax. Additionally, this
helps disambiguate from the `luau` syntax which has a different meaning
for label syntax (`::`)

chore: disambiguate lua syntax

---

lua/avante/utils/init.lua

Code blocks for files with multiple filetypes are tagged with the entire
multiple filetype combination. For example, yaml.github has a codeblock
with yaml.github tagged in the codeblock, when yaml should be used. This
updates the codeblock to only use the first filetype (and possibly fixes
other usages of `get_filetype` as well).

fix: properly highlight multi filetype code blocks

---

lua/avante/providers/openai.lua

**Fixes #1911 – 400 `invalid_type` when sending pasted images**
---
* Guarantees that **`messages[n].content` is always an _array_**, even when the original user prompt is 
*  a plain string, or  
* a single `{type = "text", text = …}` block.  
* After wrapping, the code safely `table.insert`s the image blocks produced by **img-clip.nvim**.
```lua
-- before (object with mixed keys) ❌
{ type = "text", text = "Hi", [1] = { type = "image_url", image_url = { … } } }
-- after (array of blocks) ✅
{
{ type = "text",      text = "Hi" },
{ type = "image_url", image_url = { … } }
}
```
OpenAI’s Chat Completions API accepts either
a string, or
an array of objects
Sending a bare object that mixes string keys and numeric indices violates the spec and yields:
```
Error: "API request failed with status …
```

fix(openai): wrap single text block in array before appending images

---

lua/avante/llm_tools/init.lua

When you call an o‑series model such as o4‑mini, the name python is already taken by the model’s built‑in code interpreter. Because Avante also registers a tool called python, the API returns a 400 error: “The function name 'python' is reserved for use by this model.” Issue #1890 tracks this problem.
This patch changes the tool metadata in lua/avante/llm_tools/init.lua:
- name = "python" -> name = "run_python"
To keep existing configs and scripts working, the code now adds a one‑line alias right after the original function:
```
M.run_python = M.python
```

Fix tool name conflict with o‑series models by renaming python to run_python (closes #1890)

---

lua/avante/providers/claude.lua

So, currently Claude 3.7 Sonnet gives alot of rate limit warnings that we hit when using Claude Text Editor mode, which it's kind of sad cause that beats the purpose of the Text Editor mode UI flow in the first place, which it's pretty nice.
So what I have been doing is that I activated the Text editor mode on claude-3.5-sonnet and it's been working very nicely with me, works like a charm with way less rate limit warnings.
Wondering if it would be ok to replace the old claude-3.5-instruct model which I think is no longer available.
Let me know what you think

fix: enable Claude text editor for claude-3.5 model

---

lua/avante/sidebar.lua

Hello,
I found this issue:
Passing `ask = false` to the `prompt_opts` results in a true. This should only be the case if `ask = null`.
Otherwise, even though `:AvanteChat` sets `ask = false`, the prompt defaults back to true.

opts: allow `false` to be passed as ask flag

---

lua/avante/sidebar.lua

This PR improves the visual experience when using sidebar windows in Neovim with `vim.opt.laststatus = 0`. Specifically, it hides the default status line content in sidebar windows by setting their local `statusline` option to a single space character.
This change ensures a cleaner and more minimal UI, especially in setups where the global status line is disabled.
Below are screenshots demonstrating the effect of this change when `vim.opt.laststatus = 0`:
**Before:**
**After:**

fix(Sidebar): fix: Hide default statusline when laststatus=0

---

lua/avante/api.lua
lua/avante/config.lua
lua/avante/init.lua

This PR introduces a new feature that allows users to directly start a new Avante chat session via a new API option and a dedicated keymap, even when currently in the sidebar buffer.
*   **`lua/avante/api.lua`**:
*   Adjusted the behavior of the `M.ask` function: When `opts.new_chat` is `true`, the sidebar will not be closed even if in the sidebar buffer and no question is immediately provided; instead, a new chat will be initiated.
*   **`lua/avante/config.lua`**:
*   Added a new keymap configuration `new_ask` (defaults to `<leader>an`) in the default settings to trigger a new chat session.
*   **`lua/avante/init.lua`**:
*   Added the `<Plug>(AvanteAskNew)` mapping, which calls `require("avante.api").ask({ new_chat = true })`.
*   Set up a keymap for `Config.mappings.new_ask` for user …

feat(sidebar): Add option and keymap to start a new chat directly

---

lua/avante/sidebar.lua

When the Avante sidebar is open and the **cursor is in the code window**, triggering a `VimResize` event (e.g., by resizing the terminal or Neovim GUI window) can cause the sidebar content to disappear.
The `VimResize` event triggers the `AvanteRefresh` command, which involves closing and then re-rendering the sidebar. The `old_result_lines` variable, which is crucial for diffing and updating the sidebar's content buffer, was not being reset when the `Sidebar:close` method was called.
As a result, when the sidebar was re-rendered after the `close` operation, the `update_content` function would compare the new content against a stale `old_result_lines` (from the previous, now closed, window instance). This often led to an incorrect diff calculation, resulting in an empty diff and thus no …

fix(sidebar): Reset old_result_lines in Sidebar:close to prevent content loss on resize

---

lua/avante/sidebar.lua

Noticed tab didn't work when the selected files container was toggled, so added the winids to be refreshed whenever it was toggled

fix(sidebar): make tab work when toggling selected files container

---

lua/avante/sidebar.lua

We resize the window of the selected files window based on the number of files, and allowing it to wrap doesn't really make since in that case. Can be convinced to actually support wrapped in this case tho.

fix(sidebar): do not wrap lines in selected files container

---

.gitignore
lua/avante/utils/init.lua
tests/llm_tools/helpers_spec.lua

Perceived issue:
when "data" is included in .gitignore file and the path to evaluate is "data_test/foo.txt", `is_ignored` function returns true when it should returns false.
Updates:
- Added tests for has_permission_to_access function
- Updated the is_ignored function to handle patterns that are substrings of rel_path but are not actually ignored.

Fix has_permissions_to_access when file is not ignored but patter is a substring

---

lua/avante/sidebar.lua

Was trying to toggle selected file from empty and it errored. turned out to be an easy fix, nui just sets the winid to `nil` on unmount so we should just check for it.

fix(sidebar): toggle from empty selected files container

---

lua/avante/providers/openai.lua

in some providers developed based on OpenAI, reasoning_content may be an empty string.

fix(provider.openai) reasoning_content maybe empty string

---

lua/avante/providers/claude.lua
lua/avante/sidebar.lua

**Summary:**
* Refactors `parse_response` in the Claude provider by removing the generation of `tool_use_list`, reducing complexity.  
* Unifies the sidebar's `selected_code_container` window options by using `vim.tbl_deep_extend` with base options for consistent behavior.

refactor(sidebar&claude): Simplify Claude provider and unify sidebar UI behavior

---

lua/avante/llm.lua

In the history refactoring, we ended up not retrying when the response had an error message. Here we indiscriminately retry whenever a 429 error is returned.

fix: always retry on 429 error

---

lua/avante/sidebar.lua

Was getting an error when adding a file to context when no files are selected, so this fixes that.

fix: handle error when no file selector window exists when no files

---

lua/avante/providers/init.lua

Close #1782
Allow users to define custom `parse_api_key` functions.
```
opts = {
vendors = {
["myvendor"] = {
__inherited_from = "openai",
endpoint = "https://openai-proxy.com/",
model = "claude-3.7-sonnet",
parse_api_key = function()
return require("env").apikey
end,
},                                                                                                                                                                                                                                                                         
},                                      
}
```
I haven't added additional conditional checks (such as `is_parse_api_key_set()`) for now because I found it involves too many elements. This should be the most minimal modification at present.

feature: Allow users to define custom parse_api_key functions.

---

Makefile
lua/avante/rag_service.lua
py/rag-service/Dockerfile

rag_search does not work on macos for the following reasons:
- `--network=host` doesn't work reliably on macos to expose ports
- I fixed this by specifying the ports to expose in the `docker run` command
- the container somehow does not have `git` installed
- this might've been because i was building for macos, but the change to install it in the `Dockerfile` didn't work
- the `build-image` step builds for the current platform, even though the `docker run` command runs for linux
- I added the `--platform linux/amd64` flag to the `docker build` command

fix: support rag search on macos

---

README.md
lua/avante/config.lua
lua/avante/providers/bedrock.lua
tests/providers/bedrock_spec.lua

This switches to resolving AWS credentials using the default AWS
credentials provider chain.
This has the advantage that AWS credentials are resolved in the same way
as other AWS tools do. It also supports more mechanisms now like AWS
profiles, AWS authentication via single-sign on and more.
It is a breaking change for bedrock users, as the old `BEDROCK_KEYS` env
var will no longer work, however it gives much more flexibility in terms
of authentication.
I have used this in my custom provider for quite some time successfully: https://gitlab.com/msvechla/avante-provider-bedrock.nvim
Let me know if you have some thoughts on this or other improvements ideas.
Thanks a lot!

Resolve AWS credentials using default credentials provider chain for Bedrock

---

lua/avante/providers/gemini.lua
lua/avante/providers/vertex.lua

* Check if `candidate.content` and `candidate.content.parts` exist before iterating. Fixes #1949 
* Handle all Gemini stop sequence reasons
* Add tool calling for Gemini when used through Vertex (this assumes vertex provider is only used for Gemini-like models, as i see there is a separate provider for Vertex Claude)
* Refactor out common code in `parse_curl_args` between Gemini and Vertex providers
* Have only tested with Vertex provider and `gemini-2.5-pro-preview-05-06`, do not know if it will affect other models

fix: gemini & vertex tools

---

lua/avante/llm_tools/init.lua
lua/avante/providers/claude.lua

I added claude 4 text editor tool.
It's now called `str_replace_based_edit_tool` and still doesn't support `undo_edit` 
As it may evolve differently than `str_replace_editor`, I created his own function
Should fix #2072
https://docs.anthropic.com/en/docs/agents-and-tools/tool-use/text-editor-tool#use-the-text-editor-tool

feat: add claude 4 text_editor tool

---

lua/avante/utils/environment.lua

The current method to parse the ENV from cmd is running asynchronously. Sometimes, I would keep having failures in getting the specified ENV key.
It would be better to run the command synchronously so that we can ensure that we get the value from the shell before returning.

fix(environment): run synchronously in parsing env from cmd

---

README.md
lua/avante/config.lua
lua/avante/llm_tools/bash.lua
lua/avante/llm_tools/create.lua
lua/avante/llm_tools/helpers.lua
lua/avante/llm_tools/insert.lua
lua/avante/llm_tools/replace_in_file.lua
lua/avante/llm_tools/undo_edit.lua

- Adds a new `behaviour.auto_approve_tool_permissions` configuration option to control when users are prompted before tool execution
- Provides flexible control over tool execution permissions with three modes: prompt for all (default), auto-approve all, or auto-approve specific tools only
- **Config**: Added `auto_approve_tool_permissions` field to the `behaviour` configuration table supporting boolean or string table values
- **Helpers**: Enhanced `confirm()` function to check tool permissions before showing prompts, with automatic approval based on configuration
- **Tools**: Updated all LLM tools (`bash`, `create`, `insert`, `replace_in_file`, `undo_edit`) to pass tool names for permission checking
- **Documentation**: Added configuration examples in README showing all three usage …

feat: Add auto_approve_tool_permissions config allowing the confirm dialogs to be disabled in agentic mode

---

lua/avante/providers/vertex.lua

fixes #2154 
occurs when gcloud is not installed on system. 
stderr has no value when being called, was not being handled, and additionally was not relevant to populating the api key; so the fix was just to pipe the error to `/dev/null`
**Before**
**After**

fix: hide gcloud error messages for vertex

---

Build.ps1
build.sh

fixes https://github.com/yetone/avante.nvim/issues/2193
fixes https://github.com/yetone/avante.nvim/issues/2142
Fixes an issue where the artifacts/libs were always the latest from GitHub while the source at local could be older.

feat: download only valid artifacts or build them

---

lua/avante/llm_tools/replace_in_file.lua

So that unregister_keybinding_events can correctly remove the keymap

fix: only set keymap for the current buffer in replace_in_file

---

lua/avante/llm_tools/attempt_completion.lua
lua/avante/llm_tools/bash.lua

Both the bash and attempt_completion tools weren’t checking if the arguments were partial / still being streamed, resulting in multiple confirmation popups with incomplete commands

Fix - Don’t execute incomplete streaming commands

---

lua/avante/sidebar.lua

This pull request updates the `Sidebar:initialize` function in `lua/avante/sidebar.lua` to improve file selection behavior. Specifically, it adds a check to ensure the provided file path exists before adding it to the file selector.
* [`lua/avante/sidebar.lua`](diffhunk://#diff-ddcb4139fbc53f068a08051ae32665c76507f66698fe427fcfdd384a36dce2fcL1439-R1440): Updated the `Sidebar:initialize` method to verify the existence of `filepath` using `Utils.path.is_exist_filepath` before calling `add_selected_file`.

fix: when initialize the avante, dont mark the current buffer as selected if it's a directory path

---

lua/avante/llm.lua
lua/avante/sidebar.lua
lua/avante/types.lua

Previously, when users declined tool executions (like file edits), these were treated the same as actual tool errors. This caused user-declined operations to be incorrectly tracked as failed edits and affected history message processing.
This fix introduces an `is_user_declined` field to distinguish between:
- Actual tool execution errors
- User-declined tool executions
- Successful tool executions
Changes:
- Add `is_user_declined` field to tool result types
- Detect user decline messages in LLM streaming
- Update history processing to exclude user-declined operations from failed edit tracking
- Ensure proper context handling for AI interactions
Fixes the issue where user declining an operation would incorrectly be treated as a tool failure.

fix: handle user-declined tool executions separately from errors

---

README.md
README_zh.md
lua/avante/providers/init.lua

Add support for scoped API keys by prefixing with AVANTE_ (e.g., AVANTE_ANTHROPIC_API_KEY)
Scoped keys take precedence over global keys for better isolation
Maintain full backward compatibility with existing global API keys
Update README.md and README_zh.md with comprehensive documentation
Smart handling to avoid double-prefixing and preserve command-based keys
Closes #2286

feat: scoped API key support with AVANTE_ prefix

---

lua/avante/model_selector.lua
lua/avante/providers/ollama.lua
lua/avante/types.lua

Rework or https://github.com/yetone/avante.nvim/pull/1841 on dynamic getter for copilot models.
Also sorts models just before displaying the picker so the model list is stable when initially presented.
Note that ollama provider needs `is_env_set` to return true before models are fetched. Ie,
```lua
provider = 'ollama',
providers = {
ollama = {
model = 'qwen2.5-coder:32b',
is_env_set = function()
return true
end,
},
},
```
Resulting list appears like:

feat: fetch ollama models to display in the model selector

---

lua/avante/rag_service.lua

- fix string formatting for `embed_extra` and `llm_extra` variables
#2177 
I've switched from using gsub() to string.format to handle the data. This ensures that the JSON is escaped correctly and prevents potential formatting errors.

fix: fix formatting of `embed_extra` and `llm_extra`

---

lua/avante/providers/init.lua

The current solution leads to inheritance problem. it defines `parse_api_key`, `is_env_set`, `setup` only if they are not defined at all (including parents), but  body of the functions relay on object (hard `self`) from closure.
E.g. if `azure` provider class is inherited from `openai`, `parse_api_key` will be defined ONLY once with `provider_config` for `openai`, so it reads the wrong `api_key_name`.
related issues:
* https://github.com/yetone/avante.nvim/issues/2097
* https://github.com/yetone/avante.nvim/issues/2130
related pull request:
* https://github.com/yetone/avante.nvim/pull/2098
P.S. seems this solution also is not so good as could be, but looks satisfied for me.

fix: parse_api_key inheritance problem

---

README.md
lua/avante/config.lua
lua/avante/sidebar.lua
lua/avante/utils/init.lua
lua/avante/utils/promptLogger.lua

This PR adds a prompt logging utility with two main features:
1. **Prompt Persistence**:
- All submitted prompts are saved to disk under a configurable `log_dir`.
- File names include timestamps (e.g., `avante_prompt_20250524_133012.log`).
- If enabled, a random fortune message is shown after successful save.
2. **In-Buffer Prompt Navigation**:
- Users can cycle through previous prompt logs directly inside the input buffer.
- Configurable keybindings for normal/insert mode:
```lua
prompt_logger = {
enabled = true,
log_dir = vim.fn.stdpath("cache") .. "/avante_logs",
fortune_cookie_on_success = false,
next_prompt = {
normal = "<C-n>", insert = "<C-n>",
},
prev_prompt = {
normal = "<C-p>", insert = "<C-p>",
},
}
```
- Navigation is **clamped**:
- `<C-n>` shows the next (newer) log but stops …

feat(prompt_logger): Save prompts to disk and add buffer navigation via keymaps

---

lua/avante/utils/lsp.lua

nvim-treesitter is moving to a new `main` branch which removes a lot of APIs that are currently on `master`. The current usage in avante is not compatible with the `main` branch. Luckily we should be able to remove the dependency all together with this change.

fix: remove dependency on nvim-treesitter

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/.luarc.json
.github/workflows/lua.yaml
README.md
README_zh.md
lua/avante/health.lua
lua/avante/utils/init.lua

Followup to [comment on this PR](https://github.com/yetone/avante.nvim/pull/2316#issuecomment-3000382046) where we remove all references to nvim-treesitter.

chore: remove all references to nvim-treesitter

---

Makefile
build.sh

Reverts yetone/avante.nvim#2324
‌‌‌‌‌When I tested it at the time, it was working fine on Linux, but today I found that it doesn't work on macOS, so I might need to revert that PR.

Revert "feat: obsoletes "require("avante_lib").load()""

---

lua/avante/llm_tools/get_diagnostics.lua

Was not properly returning the diagnostics from the get_diagnostics function.
One idea here as well is to properly use the diagnostic pull method `textDocument/diagnostic` so that we can request diagnostics on demand for files that haven't been opened yet.

fix: get diagnostics tool

---

lua/avante/providers/bedrock/claude.lua

This fixes https://github.com/yetone/avante.nvim/issues/2345
Tested working on my local machine, tools are called successfully

fix: error on calling transform_anthropic_usage on a nil with bedrock

---

lua/avante/llm.lua
lua/avante/utils/prompts.lua

Reference: https://docs.cursor.com/context/rules#rule-type and limited anecdotal experience
Following suit to a previous pr: https://github.com/yetone/avante.nvim/pull/2376, but separated to a different function since the logic is pretty specific and complex
TODO would be to add a tool to request cursor rules ad hoc for these "Agent Requested" rules types
Might also be a good idea to not include rule file contents from multiple sources, but rather just down a preference list. For example, only cursor files first if they exist, then claude, and so on.

feat: parse and conditionally add cursor rules to system prompt

---

lua/avante/sidebar.lua

Looks like the result container height is not respecting the input height from config `windows.input.height`
closes https://github.com/yetone/avante.nvim/issues/2377, https://github.com/yetone/avante.nvim/issues/2323

fix(sidebar): respect input height from config

---

README.md
README_zh.md
lua/avante/config.lua
lua/avante/path.lua

I don't want to checkin the `*.avanterules` in some repo and neither to add it into .gitignore, so I wish there is a chance to customize the rules locations. In additional, I also wish there is a global rules works for all projects as fallback. such as:
```lua
rules = {
project_dir = "local/",
global_dir = "/home/alice/nvim/airules/",
},
```

improve: support to customize the avanterules directories for project/global

---

lua/avante/sidebar.lua

was just closing a tab page that avante was attached to but was hidden and got this error. unsure if this is correct, but will probably quell the error notifications.

fix: handle invalid code window id

---

py/rag-service/src/main.py

**Bug Description**
Files within the `.git` directory are not being correctly ignored when a repository does not contain a `.gitignore` or `git-crypt` file.
**Root Cause**
This issue stems from the interaction between the `scan_directory` and `get_pathspec` functions.
1.  `get_pathspec` is responsible for building a `pathspec` object from ignore patterns. It always adds `".git/"` to its list of patterns by default.
2.  However, it contains a condition: `if len(patterns) <= 1: return None`.
3.  In a repository without a `.gitignore` or other ignore files, the `patterns` list only contains the default `".git/"` entry. Its length is 1, triggering the condition and causing `get_pathspec` to return `None`.
4.  The calling function, `scan_directory`, receives `None` for its `spec` variable and …

fix: rag service include git files

---

README.md
README_zh.md
lua/avante/config.lua
lua/avante/path.lua

- Add `override_prompt_dir` configuration option
- Add support for user-specified custom templates directory, overriding built-in templates
- Update documentation for `override_prompt_dir`
This PR introduces the `override_prompt_dir` setting, allowing users to override all or a portion of the built-in prompts with their own custom versions.
This change also ensures that project-level `.avanterules` files are properly recognized and take effect.

feat: enable override prompt templates directory

---

lua/avante/sidebar.lua

Before using stored window ID in Sidebar:recover_code_winhl() we should check that it is valid, otherwise we may get the following error:
Error detected while processing WinClosed Autocommands for "*": Error executing lua callback: ...le/home/dtor/projects/avante.nvim/lua/avante/sidebar.lua:221: Invalid window id: 1008
This happens when closing code window while sidebar is open/visible.

fix: don't throw errors when closing code window

---

lua/avante/file_selector.lua

#closes 2379
Before, adding an oil directory will not work because the routing of the oil directory is not parsed properly. This commit detects if the filepath is an oil directory, then parse it by removing the "oil:" from the string.

feat(file_selector): handle parsing oil directory

---

py/rag-service/src/main.py

When a file is modified, `SimpleDirectoryReader` may index a temporary file, which can cause a `ValueError`. For example: `ValueError: File /host/doodleEsc/LazyVim/lua/lazyvim/plugins/extras/ai/4913 does not exist.`
This PR prevents the `ValueError` by checking if the `abs_file_path` is a valid source file before indexing.

fix: Avoid indexing temporary files

---

lua/avante/llm_tools/replace_in_file.lua

This PR improves the robustness of the `fix_diff` function in `replace_in_file.lua` by normalizing block headers for SEARCH/REPLACE operations.
- Added logic to `fix_diff` to automatically convert alternate block header formats (e.g., `<<<<<<< SEARCH` and `>>>>>>> REPLACE`) to the expected `------- SEARCH` and `+++++++ REPLACE` forms.
- This ensures compatibility with LLM-generated diffs that may output non-standard headers, preventing parsing errors and making the tool more resilient to format variations.
Some LLMs like GPT-4.1 sometimes generate SEARCH/REPLACE block headers using different symbols (such as `<<<<<<<` and `>>>>>>>`). Previously, this could cause the tool to fail to recognize and apply these diffs correctly. The normalization logic guarantees that these alternate headers …

fix(fix_diff): added a replace substring logic

---

lua/avante/utils/init.lua

We can use str:gsub("\n", "\n") to match and count newlines. While this introduces overhead of allocating and copying a string it happens in optimized C code, and should be much more efficient than having Lua interpreter scan the string character by character and call byte() on each of them.

refactor(utils): simplify and annotate count_lines()

---

lua/avante/sidebar.lua

If we resize the window manually, avante will reset it to default layout on every keystroke, making it impossible to resize the layout ourselves.
Expected is for avante to only set the window sizes on first render, then allow user to resize if he wants.

fix: layout being resized on every keystroke

---

lua/avante/path.lua

PR #2433 introduced a specific prompt for `gpt-4.1` and set the `override` parameter in the copy method to `true`. As a result, the `.avanterules` file, which had already been copied from `override_prompt_dir` to the cache directory, is being overwritten.
The intended workflow, established in #2387, is as follows:
1.  Check if `override_prompt_dir` is available. If so, copy the `.avanterules` file from it to the project's prompt cache directory.
2.  Then, copy the system's built-in `.avanterules` to the prompt cache directory with `override` set to `false` to avoid overwriting any pre-existing `.avanterules` file.
If a user does not provide a custom _gpt4-1-agentic.avanterules, the system-level _gpt4-1-agentic.avanterules file is also copied correctly. All of this functionality has been …

Fix: Prevent custom .avanterules from being overwritten by system defaults

---

lua/avante/llm.lua

Rate limit handling seems to be broken: it starts an one-shot timer with callback that reschedules the timer each second and prints/updates messages. Simultaneously it schedules a deferred by 1 second function that cancels the timer and resumes the stream. This results in the timer executing at most once, and stream resume happening way too early.
Fix this by switching to use repeating timer with first instance executing immediately. All message handling is moved into the timer callback. Once countdown is complete the same callback will stop and destroy the timer and resume the stream.

fix(llm): fix rate limit handling

---

lua/avante/history/helpers.lua
lua/avante/history/init.lua
lua/avante/llm.lua
lua/avante/sidebar.lua
lua/avante/utils/init.lua

When updating chat history to be used in LLM request there are several instances where we do O(n^2) operations: scanning all messages to locate a tool "use" and for each use scan messages again to locate corresponding "result".
Refactor the code to scan messages once collecting tool uses and results together, and then do 2nd scan to drop incomplete tool invocations and refresh "view" and "edit" results with the latest content.
Also reduce number of pre-scan loops (where we discard partially generated messages or messages that are not interesting or too-old) by combining them when possible.
This reduces time to scan initial 417 messages on my system (which result in 576 final messages) from 0.32 to 0.12 seconds.

refactor(history): reduce computational complexity when handling history

---

lua/avante/sidebar.lua

Under the hood vim.list_extend() does the same loop over the source table and uses table.insert() to append the values to the destination table, so using a temporary table makes little sense.
Switch to directly inserting (appending) values into history_lines table.

refactor(sidebar): avoid temporary table in Sidebar:update_content()

---

lua/avante/api.lua
lua/avante/llm_tools/helpers.lua
lua/avante/sidebar.lua
lua/avante/ui/confirm.lua
lua/cmp_avante/commands.lua

Maintaining a separate winids table and keeping it in sync with winids in NuiSplits is cumbersome, let's rework sidebar to only rely on data in splits.

Refactor sidebar code to avoid maintaining separate winid table

---

lua/avante/llm.lua
lua/avante/templates/_task-guidelines.avanterules

- Refactor TODOs handling: move logic to `context_messages` instead of using `template_opts`
- Remove the TODOs section from `_task-guidelines.avanterules` template

refactor: refactor TODO handling to context messages

---

README.md
README_zh.md

The `build` opt must be fun(LazyPlugin) or string or false or a list of
build commands, not fun():string
Ref: https://lazy.folke.io/spec

doc: the `build` opt must return a string value

---

lua/avante/sidebar.lua

Current implementation always says that first 5 lines of code is shown when selected code does not fully fit into its window. This is not correct as the window can be resized, may have a header occupying one line, and the lines may not be the first ones. Also the wording is awkward.
Correct these issues by checking current window height, accounting for the potential header presence by checking sidebar.enabled config flag, and updating the message format to be more concise:
" Selected Code (4/15 lines)"
While at it switch to using Utils.count_lines() which does not need creating temporary tables.
Note that this does not deal with the header info being stale after resizing sidebar windows.

fix(sidebar): account for sidebar header on/off for selected code

---

lua/avante/sidebar.lua

"filetype" should not be passed directly to vim.treesitter.start() as "lang" argument. While it usually works, it breaks on help files whose filetype is "help" but language should be "vimdoc".
Use vim.treesitter.language.get_lang() to map filetype to language before passing it to treesitter's start() call.
Fixes: 10c0a8d ("feat(sidebar): allow external users identify selected code buffer")

fix(sidebar): do not error when selecting text from help window

---

lua/avante/sidebar.lua

Current sidebar code tries to align sidebar header manually by fetching window width and calculating appropriate padding. Unfortunately calculations become invalid when sidebar is resized.
Winbar (which is used for displaying headers) has facilities to automatically align its components which work properly even if a window is resized. These facilities were used in the sidebar code before but for some reason were replaced with manual padding. Unfortunately there are no comments explaining the decision.
Fix the alignment issues by using winbar alignment directives (%=).

fix(sidebar): keep header aligned when sidebar width changed

---

lua/avante/providers/openai.lua

Hi everyone!
I'm submitting this patch to fix an HTTP 422 error that is produced when running avante against open-webui and LiteLLM. My company insists that I use our LLMs through this and I was only able to get it to work with this patch. I tested against my company's setup and also against my personal OpenAI account and was able to do what I normally do (chat and make some edits from visual mode).
Review and feedback appreciated. Thank you!

fix: set the content property to the empty string

---

lua/avante/config.lua
lua/avante/sidebar.lua
lua/avante/utils/promptLogger.lua

New prompt logger
1. enable user to cycle through prompt history with current user input included, for example, users can use `<C-n>` to get their input back if previous prompt was brought accidentally by user with `<C-p>`. This behaves same as shell like bash/zsh.
1. prompt history is updated instantly.
1. save all history in one file -- `~/.cache/nvim/avante_prompts.log`

fix: re-implement prompt logger

---

lua/avante/config.lua

If file containing information about last used model contains invalid or obsolete data remove it (or rename so that it can be inspected) instead of throwing errors at user every time they open their editor.

fix(config): remove last used model data if it is damaged

---

lua/avante/config.lua
lua/avante/sidebar.lua

Enable user to use `x` to toggle code window, so that user can view result in sidebar with a wide window. User can also use `x` to restore the code window.

feat: toggle code window from result container in sidebar

---

lua/avante/api.lua

When I lazy load AvanteAskNew, I get an error that the sidebar is `nil`. This fixes that error.

fix: allow lazy loading AvanteAskNew

---

lua/avante/api.lua

Lazy loading on `AvanteEdit` does not work the first time invoked because the sidebar has not initialized yet. Thus initialize the sidebar first before continuing.

fix: lazy load AvanteEdit

---

README.md
README_zh.md
lua/avante/config.lua
lua/avante/init.lua
lua/avante/selection.lua

Selection hint that is displayed immediately upon entering visual mode ([<leader>aa: ask, <leader>ae: edit]) gets old pretty quickly. Add a config option to control when the hint is displayed:
selection = {
enabled = true,
hint_display = "delayed",
},
The "hint_display" option recognizes the following values:
- "immediate" results in the hint being shown immediately after entering visual mode. This is the old behavior.
- "delayed" causes the hint be displayed only if the cursor has not been moved for vim.o.updatetime milliseconds. This is the new default.
- "none" suppresses showing the hint completely.
Unfortunately "CursorHold" event is not emitted in visual mode so we have to emulate it using Utils.debounce().
This is a breaking change because selection behavior was controller by …

feat!(selection): do not display hint immediately

---

lua/avante/config.lua
lua/avante/sidebar.lua

This commit adds a configuration option to set a maximum height for the selected files window. This is because at the moment, if you attached a lot of selected files, it would end up taking the whole chat buffer which made the user experience really rough.
After adding this configuration option, I just modified the sidebar logic so that instead of deciding between the minimum of the maximum number of height lines in the vim window, or the number of selected files, we are now picking between the configured max lines height, and the number of selected files, which should make the UX much better.
Closes #2615

Add config to limit max height for selected files

---

lua/avante/llm.lua

User input is wrapped in tag `<task>`, which seems to be not necessary and causing unwanted behavior in `legacy` mode.

fix: wrap user input in task only in agentic mode

---

lua/avante/utils/root.lua

Currently project root is tied with buffer number, cache of project root for the buffer should be invalid if the buffer name changed.

fix: reset cache for project root if buf name changed

---

lua/avante/llm.lua

The headers dump file was deleted by plenary.nvim, please see see https://github.com/nvim-lua/plenary.nvim/blob/b9fd5226c2f76c951fc8ed5923d85e4de065e509/lua/plenary/curl.lua#L268, the change is to create a log file for response headers with its content copied from the headers dump file from plenary.nvim.

fix: log response headers for debug

---

lua/avante/utils/root.lua

Use common files/folders such as `Makefile` / `CMakeLists.txt` for C++ project or `pom.xml` for Java project to find project root, remove `lua` which cannot be a file/folder to mark project root.

fix: use common files to find project root

---

lua/avante/config.lua
lua/avante/llm_tools/init.lua

This pull request adds support for optionally including a "Generated-by" line in git commit messages, indicating the provider and model used for generation. The feature is controlled by a new configuration option.
Configuration changes:
* Added the `include_generated_by_commit_line` option to the `behaviour` section in `config.lua` to control whether the "Generated-by" line is included in commit messages.
Commit message generation changes:
* Updated the `git_commit` tool to append a `Generated-by: <provider>/<model>` line to commit messages when the new configuration option is enabled.

feat(git): Add configuration option for 'Generated-by' line in commit

---

lua/avante/libs/acp_client.lua
lua/avante/llm.lua

- Implement automatic ACP session recovery for avante.nvim's Claude Code integration
- Add intelligent history truncation to maintain context while avoiding token limits
- Filter ACP stderr messages to reduce user confusion during recovery
- Resolve "Session not found" errors when restarting Neovim
- Enhanced `_stream_acp` function in `lua/avante/llm.lua` with automatic session recovery
- Added `truncate_history_for_recovery` function for intelligent message truncation
- Updated `lua/avante/libs/acp_client.lua` to filter session-related error messages
- Session recovery is user-configurable through `session_recovery` options
Fixes #2710

feat: add automatic ACP session recovery with intelligent history truncation

---

lua/avante/config.lua
lua/avante/libs/acp_client.lua
lua/avante/llm.lua

This adds [goose](https://block.github.io/goose/) as an ACP provider. 
To get goose to work appropriately I had to:
- make sure that the previously session ids aren't passed in, because the goose acp doesn't currently support session loading
- make sure that multiple '\n' are not passed in, this causes the zed ACP library that goose uses to complain.

Add Goose as an ACP provider

---

lua/avante/providers/init.lua
plugin/avante.lua

Trying out the new acp providers and want the ability to easily swap between those and the native providers. this change adds support for that while updating the autocomplete accordingly

feat: allow switching between acp providers with AvanteSwitchProvider
